from __future__ import annotations

from typing import Any


API_SCHEMAS: dict[str, Any] = {
    "ApiEnvelope": {
        "type": "object",
        "required": ["code", "message", "data", "meta"],
        "properties": {
            "code": {"type": "integer"},
            "message": {"type": "string"},
            "data": {},
            "meta": {
                "type": "object",
                "required": ["request_id"],
                "properties": {"request_id": {"type": ["string", "null"]}},
                "additionalProperties": True,
            },
        },
    },
    "Summary": {
        "type": "object",
        "required": [
            "raw_rows",
            "cleaned_rows",
            "removed_rows",
            "duplicate_rows",
            "invalid_price_rows",
            "missing_brand_rows",
            "unique_users",
            "unique_sessions",
            "total_sales",
        ],
        "properties": {
            "raw_rows": {"type": "integer"},
            "cleaned_rows": {"type": "integer"},
            "removed_rows": {"type": "integer"},
            "duplicate_rows": {"type": "integer"},
            "invalid_price_rows": {"type": "integer"},
            "missing_brand_rows": {"type": "integer"},
            "unique_users": {"type": "integer"},
            "unique_sessions": {"type": "integer"},
            "total_sales": {"type": "number"},
        },
    },
    "NamedValue": {
        "type": "object",
        "required": ["name", "value"],
        "properties": {
            "name": {"type": "string"},
            "value": {"type": "number"},
            "orders": {"type": "number"},
        },
    },
    "DateValue": {
        "type": "object",
        "required": ["date", "value"],
        "properties": {"date": {"type": "string"}, "value": {"type": "number"}},
    },
    "FunnelStep": {
        "type": "object",
        "required": ["step", "sessions", "rate_from_previous"],
        "properties": {
            "step": {"type": "string"},
            "sessions": {"type": "integer"},
            "rate_from_previous": {"type": "number"},
        },
    },
    "SessionFunnel": {
        "type": "object",
        "required": ["totals", "steps"],
        "properties": {
            "totals": {
                "type": "object",
                "properties": {
                    "sessions": {"type": "integer"},
                    "view_sessions": {"type": "integer"},
                    "cart_sessions": {"type": "integer"},
                    "purchase_sessions": {"type": "integer"},
                    "view_to_cart_rate": {"type": "number"},
                    "cart_to_purchase_rate": {"type": "number"},
                    "view_to_purchase_rate": {"type": "number"},
                    "avg_purchase_latency_minutes": {"type": "number"},
                    "revenue": {"type": "number"},
                    "avg_order_value": {"type": "number"},
                },
                "additionalProperties": True,
            },
            "steps": {"type": "array", "items": {"$ref": "#/components/schemas/FunnelStep"}},
        },
    },
    "DailyConversion": {
        "type": "object",
        "required": ["date", "sessions", "purchase_sessions", "view_to_purchase_rate", "revenue"],
        "properties": {
            "date": {"type": "string"},
            "sessions": {"type": "integer"},
            "purchase_sessions": {"type": "integer"},
            "view_to_purchase_rate": {"type": "number"},
            "revenue": {"type": "number"},
        },
    },
    "ProductConversion": {
        "type": "object",
        "required": [
            "product_id",
            "brand",
            "category_level1",
            "views",
            "carts",
            "purchases",
            "view_to_cart_rate",
            "cart_to_purchase_rate",
            "revenue",
        ],
        "properties": {
            "product_id": {"type": "string"},
            "brand": {"type": "string"},
            "category_level1": {"type": "string"},
            "views": {"type": "integer"},
            "carts": {"type": "integer"},
            "purchases": {"type": "integer"},
            "view_to_cart_rate": {"type": "number"},
            "cart_to_purchase_rate": {"type": "number"},
            "revenue": {"type": "number"},
        },
    },
    "JourneySummary": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "sessions": {"type": "integer"},
            "unique_paths": {"type": "integer"},
            "purchase_sessions": {"type": "integer"},
            "cart_sessions": {"type": "integer"},
            "purchase_path_rate": {"type": "number"},
            "cart_path_rate": {"type": "number"},
            "revenue": {"type": "number"},
            "avg_steps": {"type": "number"},
            "avg_duration_seconds": {"type": "number"},
            "top_path": {"type": ["object", "null"]},
            "top_exit_event": {"type": ["object", "null"]},
            "top_transition": {"type": ["object", "null"]},
            "recommended_action": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "JourneyPath": {
        "type": "object",
        "properties": {
            "path_signature": {"type": "string"},
            "sessions": {"type": "integer"},
            "cart_sessions": {"type": "integer"},
            "purchase_sessions": {"type": "integer"},
            "revenue": {"type": "number"},
            "avg_steps": {"type": "number"},
            "avg_duration_seconds": {"type": "number"},
            "conversion_rate": {"type": "number"},
            "cart_rate": {"type": "number"},
        },
        "additionalProperties": True,
    },
    "JourneyTransition": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "from_event": {"type": "string"},
            "to_event": {"type": "string"},
            "transitions": {"type": "integer"},
            "sessions": {"type": "integer"},
            "purchase_sessions": {"type": "integer"},
            "revenue": {"type": "number"},
            "conversion_rate": {"type": "number"},
            "dropoff_hint": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "JourneyExitEvent": {
        "type": "object",
        "properties": {
            "last_event": {"type": "string"},
            "sessions": {"type": "integer"},
            "purchase_sessions": {"type": "integer"},
            "revenue": {"type": "number"},
            "avg_steps": {"type": "number"},
            "exit_share": {"type": "number"},
            "purchase_rate": {"type": "number"},
        },
        "additionalProperties": True,
    },
    "JourneyPurchasePath": {
        "type": "object",
        "properties": {
            "path_signature": {"type": "string"},
            "purchase_sessions": {"type": "integer"},
            "revenue": {"type": "number"},
            "avg_steps": {"type": "number"},
            "avg_duration_seconds": {"type": "number"},
        },
        "additionalProperties": True,
    },
    "ForecastingSummary": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "input_snapshot": {"type": "object"},
            "forecast_horizon_days": {"type": "integer"},
            "training_window_days": {"type": "integer"},
            "backtest_window_days": {"type": "integer"},
            "history_days": {"type": "integer"},
            "driver_history_rows": {"type": "integer"},
            "max_driver_history_rows": {"type": "integer"},
            "history_range": {"type": "object"},
            "entity_count": {"type": "integer"},
            "site_forecast_gmv": {"type": "number"},
            "site_forecast_purchase_count": {"type": "number"},
            "risk_count": {"type": "integer"},
            "high_risk_count": {"type": "integer"},
            "quality_status": {"type": "string"},
            "top_risk": {"type": ["object", "null"]},
            "recommended_action": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "ForecastingSeriesPoint": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "dt": {"type": "string"},
            "scope": {"type": "string"},
            "entity_key": {"type": "string"},
            "entity_label": {"type": "string"},
            "metric": {"type": "string"},
            "forecast_value": {"type": "number"},
            "lower_bound": {"type": "number"},
            "upper_bound": {"type": "number"},
            "history_days": {"type": "integer"},
            "model_name": {"type": "string"},
            "fallback_reason": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "ForecastingEntity": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "scope": {"type": "string"},
            "entity_key": {"type": "string"},
            "entity_label": {"type": "string"},
            "forecast_gmv": {"type": "number"},
            "forecast_purchase_count": {"type": "number"},
            "recent_gmv": {"type": "number"},
            "expected_change_rate": {"type": "number"},
            "history_days": {"type": "integer"},
            "risk_level": {"type": "string"},
            "risk_score": {"type": "integer"},
            "model_name": {"type": "string"},
            "fallback_reason": {"type": "string"},
            "recommended_action": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "ForecastingBacktestPoint": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "dt": {"type": "string"},
            "scope": {"type": "string"},
            "entity_key": {"type": "string"},
            "entity_label": {"type": "string"},
            "metric": {"type": "string"},
            "actual": {"type": "number"},
            "forecast": {"type": "number"},
            "absolute_error": {"type": "number"},
            "error": {"type": "number"},
            "model_name": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "ForecastingRisk": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "risk_id": {"type": "string"},
            "scope": {"type": "string"},
            "entity_key": {"type": "string"},
            "entity_label": {"type": "string"},
            "severity": {"type": "string"},
            "risk_type": {"type": "string"},
            "metric": {"type": "string"},
            "evidence": {"type": "object"},
            "recommended_action": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "ForecastingQuality": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "passed": {"type": "boolean"},
            "quality_status": {"type": "string"},
            "checks": {"type": "array", "items": {"type": "object"}},
            "metrics": {"type": "object"},
        },
        "additionalProperties": True,
    },
    "AffinitySummary": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "input_snapshot": {"type": "object"},
            "node_count": {"type": "integer"},
            "edge_count": {"type": "integer"},
            "community_count": {"type": "integer"},
            "opportunity_count": {"type": "integer"},
            "eligible_session_count": {"type": "integer"},
            "min_support": {"type": "integer"},
            "quality_status": {"type": "string"},
            "sparse_graph": {"type": "boolean"},
            "strongest_edge": {"type": ["object", "null"]},
            "top_opportunity": {"type": ["object", "null"]},
            "recommended_action": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "AffinityNode": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "entity_id": {"type": "string"},
            "entity_type": {"type": "string"},
            "entity_label": {"type": "string"},
            "brand": {"type": "string"},
            "category_level1": {"type": "string"},
            "views": {"type": "integer"},
            "carts": {"type": "integer"},
            "purchases": {"type": "integer"},
            "revenue": {"type": "number"},
            "degree": {"type": "integer"},
            "weighted_degree": {"type": "number"},
            "community_id": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "AffinityEdge": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "source_id": {"type": "string"},
            "target_id": {"type": "string"},
            "source_type": {"type": "string"},
            "target_type": {"type": "string"},
            "source_label": {"type": "string"},
            "target_label": {"type": "string"},
            "source_brand": {"type": "string"},
            "target_brand": {"type": "string"},
            "source_category": {"type": "string"},
            "target_category": {"type": "string"},
            "relation_type": {"type": "string"},
            "support": {"type": "integer"},
            "confidence": {"type": "number"},
            "lift": {"type": "number"},
            "jaccard": {"type": "number"},
            "revenue_overlap": {"type": "number"},
            "sample_sessions": {"type": "integer"},
            "quality_status": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "AffinityCommunity": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "community_id": {"type": "string"},
            "category_level1": {"type": "string"},
            "node_count": {"type": "integer"},
            "edge_count": {"type": "integer"},
            "revenue": {"type": "number"},
            "top_entities": {"type": "array", "items": {"type": "string"}},
            "recommended_action": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "AffinityOpportunity": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "opportunity_id": {"type": "string"},
            "type": {"type": "string"},
            "primary_entity": {"type": "string"},
            "primary_label": {"type": "string"},
            "related_entity": {"type": "string"},
            "related_label": {"type": "string"},
            "reason_codes": {"type": "array", "items": {"type": "string"}},
            "estimated_revenue_pool": {"type": "number"},
            "confidence": {"type": "number"},
            "lift": {"type": "number"},
            "support": {"type": "integer"},
            "risk_level": {"type": "string"},
            "action": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "AffinityQuality": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "quality_status": {"type": "string"},
            "passed": {"type": "boolean"},
            "session_count": {"type": "integer"},
            "eligible_session_count": {"type": "integer"},
            "edge_count": {"type": "integer"},
            "min_support": {"type": "integer"},
            "sparse_graph": {"type": "boolean"},
            "warnings": {"type": "array", "items": {"type": "string"}},
            "checks": {"type": "array", "items": {"type": "object"}},
        },
        "additionalProperties": True,
    },
    "CohortSummary": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "input_snapshot": {"type": "object"},
            "cohort_unit": {"type": "string"},
            "user_count": {"type": "integer"},
            "purchase_user_count": {"type": "integer"},
            "repeat_purchase_user_count": {"type": "integer"},
            "repeat_purchase_rate": {"type": "number"},
            "median_days_to_second_purchase": {"type": "string"},
            "avg_revenue_per_purchase_user": {"type": "number"},
            "cohort_revenue": {"type": "number"},
            "high_risk_cohort_count": {"type": "integer"},
            "quality_status": {"type": "string"},
            "sparse_cohorts": {"type": "array", "items": {"type": "string"}},
            "recommended_action": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "CohortRetentionCell": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "cohort": {"type": "string"},
            "period_index": {"type": "integer"},
            "cohort_users": {"type": "integer"},
            "active_users": {"type": "integer"},
            "purchase_users": {"type": "integer"},
            "retention_rate": {"type": "number"},
            "repurchase_rate": {"type": "number"},
            "revenue": {"type": "number"},
            "quality_status": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "CohortRepurchaseInterval": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "bucket": {"type": "string"},
            "users": {"type": "integer"},
            "share": {"type": "number"},
            "avg_revenue": {"type": "number"},
        },
        "additionalProperties": True,
    },
    "CohortValueCurve": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "cohort": {"type": "string"},
            "period_index": {"type": "integer"},
            "revenue": {"type": "number"},
            "cumulative_revenue": {"type": "number"},
            "revenue_per_purchase_user": {"type": "number"},
            "purchase_users": {"type": "integer"},
        },
        "additionalProperties": True,
    },
    "CohortSegment": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "segment_id": {"type": "string"},
            "cohort": {"type": "string"},
            "category_level1": {"type": "string"},
            "users": {"type": "integer"},
            "repeat_purchase_users": {"type": "integer"},
            "repeat_purchase_rate": {"type": "number"},
            "revenue": {"type": "number"},
            "risk_level": {"type": "string"},
            "reason_codes": {"type": "array", "items": {"type": "string"}},
            "recommended_action": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "CohortQuality": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "quality_status": {"type": "string"},
            "passed": {"type": "boolean"},
            "history_days": {"type": "integer"},
            "cohort_count": {"type": "integer"},
            "min_cohort_users": {"type": "integer"},
            "sparse_cohorts": {"type": "array", "items": {"type": "string"}},
            "warnings": {"type": "array", "items": {"type": "string"}},
            "checks": {"type": "array", "items": {"type": "object"}},
        },
        "additionalProperties": True,
    },
    "PortfolioSummary": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "input_snapshot": {"type": "object"},
            "quality_status": {"type": "string"},
            "total_revenue": {"type": "number"},
            "total_purchases": {"type": "integer"},
            "category_count": {"type": "integer"},
            "brand_count": {"type": "integer"},
            "price_band_count": {"type": "integer"},
            "warnings": {"type": "array", "items": {"type": "string"}},
            "top_category": {"type": ["object", "null"]},
            "top_product_revenue_share": {"type": "number"},
            "product_revenue_hhi": {"type": "number"},
            "opportunity_count": {"type": "integer"},
            "recommended_action": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "PortfolioCategoryMix": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "category_level1": {"type": "string"},
            "views": {"type": "integer"},
            "carts": {"type": "integer"},
            "purchases": {"type": "integer"},
            "revenue": {"type": "number"},
            "avg_price": {"type": ["number", "null"]},
            "view_to_cart_rate": {"type": ["number", "null"]},
            "view_to_purchase_rate": {"type": ["number", "null"]},
            "cart_to_purchase_rate": {"type": ["number", "null"]},
            "revenue_share": {"type": ["number", "null"]},
            "purchase_share": {"type": ["number", "null"]},
        },
        "additionalProperties": True,
    },
    "PortfolioBrandMix": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "category_level1": {"type": "string"},
            "brand": {"type": "string"},
            "views": {"type": "integer"},
            "carts": {"type": "integer"},
            "purchases": {"type": "integer"},
            "revenue": {"type": "number"},
            "avg_price": {"type": ["number", "null"]},
            "view_to_purchase_rate": {"type": ["number", "null"]},
            "revenue_share": {"type": ["number", "null"]},
            "purchase_share": {"type": ["number", "null"]},
        },
        "additionalProperties": True,
    },
    "PortfolioPriceBand": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "category_level1": {"type": "string"},
            "price_band": {"type": "string"},
            "purchases": {"type": "integer"},
            "revenue": {"type": "number"},
            "avg_price": {"type": ["number", "null"]},
            "revenue_share": {"type": ["number", "null"]},
            "purchase_share": {"type": ["number", "null"]},
        },
        "additionalProperties": True,
    },
    "PortfolioProductConcentration": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "rank": {"type": "integer"},
            "product_id": {"type": "string"},
            "category_level1": {"type": "string"},
            "brand": {"type": "string"},
            "purchases": {"type": "integer"},
            "revenue": {"type": "number"},
            "revenue_share": {"type": "number"},
            "purchase_share": {"type": "number"},
            "hhi_contribution": {"type": "number"},
        },
        "additionalProperties": True,
    },
    "PortfolioOpportunity": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "opportunity_type": {"type": "string"},
            "entity_type": {"type": "string"},
            "entity_id": {"type": "string"},
            "price_band": {"type": ["string", "null"]},
            "impact_score": {"type": "number"},
            "confidence": {"type": "number"},
            "views": {"type": ["integer", "null"]},
            "purchases": {"type": "integer"},
            "revenue": {"type": "number"},
            "reason_codes": {"type": "array", "items": {"type": "string"}},
        },
        "additionalProperties": True,
    },
    "PortfolioQuality": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "quality_status": {"type": "string"},
            "passed": {"type": "boolean"},
            "rows": {"type": "integer"},
            "purchase_rows": {"type": "integer"},
            "history_days": {"type": "integer"},
            "category_count": {"type": "integer"},
            "brand_count": {"type": "integer"},
            "valid_price_purchase_rate": {"type": "number"},
            "price_band_count": {"type": "integer"},
            "warnings": {"type": "array", "items": {"type": "string"}},
            "checks": {"type": "array", "items": {"type": "object"}},
        },
        "additionalProperties": True,
    },
    "CartSummary": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "quality_status": {"type": "string"},
            "configured_input_path": {"type": "string"},
            "actual_input_path": {"type": "string"},
            "cart_product_sessions": {"type": "integer"},
            "abandoned_sessions": {"type": "integer"},
            "recovered_sessions": {"type": "integer"},
            "explicit_remove_sessions": {"type": "integer"},
            "cart_value": {"type": "number"},
            "abandoned_value": {"type": "number"},
            "abandonment_rate": {"type": "number"},
            "recovery_rate": {"type": "number"},
            "remove_rate": {"type": "number"},
            "category_count": {"type": "integer"},
            "product_count": {"type": "integer"},
            "queue_count": {"type": "integer"},
            "warnings": {"type": "array", "items": {"type": "string"}},
        },
        "additionalProperties": True,
    },
    "CartCategorySegment": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "category_level1": {"type": "string"},
            "cart_product_sessions": {"type": "integer"},
            "cart_events": {"type": "integer"},
            "remove_events": {"type": "integer"},
            "recovered_sessions": {"type": "integer"},
            "explicit_remove_sessions": {"type": "integer"},
            "abandoned_sessions": {"type": "integer"},
            "cart_value": {"type": "number"},
            "abandoned_value": {"type": "number"},
            "recovery_rate": {"type": ["number", "null"]},
            "abandonment_rate": {"type": ["number", "null"]},
            "remove_rate": {"type": ["number", "null"]},
        },
        "additionalProperties": True,
    },
    "CartProductSegment": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "rank": {"type": "integer"},
            "product_id": {"type": "string"},
            "category_level1": {"type": "string"},
            "brand": {"type": "string"},
            "cart_product_sessions": {"type": "integer"},
            "cart_events": {"type": "integer"},
            "remove_events": {"type": "integer"},
            "recovered_sessions": {"type": "integer"},
            "explicit_remove_sessions": {"type": "integer"},
            "abandoned_sessions": {"type": "integer"},
            "avg_price": {"type": ["number", "null"]},
            "abandoned_value": {"type": "number"},
            "recovery_rate": {"type": ["number", "null"]},
            "abandonment_rate": {"type": ["number", "null"]},
            "remove_rate": {"type": ["number", "null"]},
            "priority_score": {"type": "number"},
        },
        "additionalProperties": True,
    },
    "CartRecoveryQueueItem": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "entity_type": {"type": "string"},
            "entity_id": {"type": "string"},
            "entity_label": {"type": "string"},
            "recovery_action": {"type": "string"},
            "priority_score": {"type": "number"},
            "confidence": {"type": "number"},
            "cart_product_sessions": {"type": "integer"},
            "abandoned_sessions": {"type": "integer"},
            "abandoned_value": {"type": "number"},
            "abandonment_rate": {"type": ["number", "null"]},
            "remove_rate": {"type": ["number", "null"]},
            "reason_codes": {"type": "array", "items": {"type": "string"}},
        },
        "additionalProperties": True,
    },
    "CartQuality": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "quality_status": {"type": "string"},
            "cart_event_rows": {"type": "integer"},
            "remove_event_rows": {"type": "integer"},
            "cart_product_sessions": {"type": "integer"},
            "history_days": {"type": "integer"},
            "min_cart_sessions": {"type": "integer"},
            "min_history_days": {"type": "integer"},
            "warnings": {"type": "array", "items": {"type": "string"}},
        },
        "additionalProperties": True,
    },
    "AttributionSummary": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "quality_status": {"type": "string"},
            "configured_input_path": {"type": "string"},
            "actual_input_path": {"type": "string"},
            "purchase_rows": {"type": "integer"},
            "purchase_sessions": {"type": "integer"},
            "attributable_sessions": {"type": "integer"},
            "attributable_purchases": {"type": "integer"},
            "attribution_coverage_rate": {"type": "number"},
            "total_purchase_revenue": {"type": "number"},
            "assisted_revenue": {"type": "number"},
            "avg_touchpoints_before_purchase": {"type": "number"},
            "avg_minutes_before_purchase": {"type": "number"},
            "multi_touch_purchase_rate": {"type": "number"},
            "entity_count": {"type": "integer"},
            "assist_opportunity_count": {"type": "integer"},
            "warnings": {"type": "array", "items": {"type": "string"}},
        },
        "additionalProperties": True,
    },
    "AttributionModel": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "entity_type": {"type": "string"},
            "entity_count": {"type": "integer"},
            "first_touch_revenue": {"type": "number"},
            "last_touch_revenue": {"type": "number"},
            "linear_assisted_revenue": {"type": "number"},
            "time_decay_assisted_revenue": {"type": "number"},
            "direct_revenue": {"type": "number"},
        },
        "additionalProperties": True,
    },
    "AttributionEntity": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "rank": {"type": "integer"},
            "entity_type": {"type": "string"},
            "entity_id": {"type": "string"},
            "entity_label": {"type": "string"},
            "touch_sessions": {"type": "integer"},
            "assisted_purchase_sessions": {"type": "integer"},
            "direct_purchase_sessions": {"type": "integer"},
            "first_touch_revenue": {"type": "number"},
            "last_touch_revenue": {"type": "number"},
            "linear_assisted_revenue": {"type": "number"},
            "time_decay_assisted_revenue": {"type": "number"},
            "direct_revenue": {"type": "number"},
            "assist_to_direct_ratio": {"type": ["number", "null"]},
            "assist_rate": {"type": ["number", "null"]},
            "avg_position_before_purchase": {"type": ["number", "null"]},
            "avg_minutes_before_purchase": {"type": ["number", "null"]},
            "cart_touchpoints": {"type": "integer"},
            "view_touchpoints": {"type": "integer"},
            "remove_negative_signal_count": {"type": "integer"},
            "confidence": {"type": "number"},
            "reason_codes": {"type": ["array", "null"], "items": {"type": "string"}},
        },
        "additionalProperties": True,
    },
    "AttributionPath": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "path_pattern": {"type": "string"},
            "sessions": {"type": "integer"},
            "purchase_sessions": {"type": "integer"},
            "revenue": {"type": "number"},
            "conversion_rate": {"type": ["number", "null"]},
            "median_latency_minutes": {"type": ["number", "null"]},
            "sample_size": {"type": "integer"},
        },
        "additionalProperties": True,
    },
    "AttributionAssist": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "entity_type": {"type": "string"},
            "entity_id": {"type": "string"},
            "entity_label": {"type": "string"},
            "suggested_action": {"type": "string"},
            "priority_score": {"type": "number"},
            "confidence": {"type": "number"},
            "time_decay_assisted_revenue": {"type": "number"},
            "linear_assisted_revenue": {"type": "number"},
            "direct_revenue": {"type": "number"},
            "assist_to_direct_ratio": {"type": ["number", "null"]},
            "assisted_purchase_sessions": {"type": "integer"},
            "touch_sessions": {"type": "integer"},
            "reason_codes": {"type": ["array", "null"], "items": {"type": "string"}},
        },
        "additionalProperties": True,
    },
    "AttributionQuality": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "quality_status": {"type": "string"},
            "purchase_rows": {"type": "integer"},
            "purchase_sessions": {"type": "integer"},
            "attributable_sessions": {"type": "integer"},
            "attribution_coverage_rate": {"type": "number"},
            "session_missing_rate": {"type": "number"},
            "valid_purchase_price_rate": {"type": "number"},
            "history_days": {"type": "integer"},
            "warnings": {"type": "array", "items": {"type": "string"}},
        },
        "additionalProperties": True,
    },
    "OptimizationSummary": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "solver_status": {"type": "string"},
            "objective_value": {"type": "number"},
            "runtime_seconds": {"type": "number"},
            "optimality_gap": {"type": ["number", "null"]},
            "candidate_count": {"type": "integer"},
            "selected_count": {"type": "integer"},
            "total_budget": {"type": "number"},
            "used_budget": {"type": "number"},
            "budget_utilization": {"type": "number"},
            "slot_count": {"type": "integer"},
            "used_slots": {"type": "integer"},
            "slot_utilization": {"type": "number"},
            "expected_incremental_gmv": {"type": "number"},
            "expected_incremental_purchases": {"type": "number"},
            "average_risk_score": {"type": "number"},
            "category_allocation": {"type": "object"},
            "action_allocation": {"type": "object"},
            "causal_caveat": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "OptimizationPlanItem": {
        "type": "object",
        "properties": {
            "product_id": {"type": "string"},
            "brand": {"type": "string"},
            "category_level1": {"type": "string"},
            "action": {"type": "string"},
            "action_type": {"type": "string"},
            "cost": {"type": "number"},
            "expected_incremental_gmv": {"type": "number"},
            "expected_incremental_purchases": {"type": "number"},
            "objective_contribution": {"type": "number"},
            "confidence_weight": {"type": "number"},
            "risk_score": {"type": "number"},
            "views": {"type": "integer"},
            "purchases": {"type": "integer"},
            "baseline_gmv": {"type": "number"},
            "avg_price": {"type": "number"},
        },
        "additionalProperties": True,
    },
    "OptimizationCandidate": {
        "type": "object",
        "properties": {
            "product_id": {"type": "string"},
            "brand": {"type": "string"},
            "category_level1": {"type": "string"},
            "views": {"type": "integer"},
            "carts": {"type": "integer"},
            "purchases": {"type": "integer"},
            "revenue": {"type": "number"},
            "avg_price": {"type": "number"},
            "purchase_rate_shrunk": {"type": "number"},
            "confidence_weight": {"type": "number"},
            "risk_score": {"type": "number"},
            "baseline_gmv": {"type": "number"},
        },
        "additionalProperties": True,
    },
    "OptimizationQuality": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "candidate_count": {"type": "integer"},
            "selected_count": {"type": "integer"},
            "eligible_count": {"type": "integer"},
            "solver_status": {"type": "string"},
            "budget_feasible": {"type": "boolean"},
            "slot_feasible": {"type": "boolean"},
            "category_cap": {"type": "integer"},
            "brand_cap": {"type": "integer"},
            "min_views": {"type": "integer"},
            "min_confidence": {"type": "number"},
        },
        "additionalProperties": True,
    },
    "RecommendationSummary": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "input_snapshot": {"type": "object"},
            "feature_window": {"type": "object"},
            "generated_at": {"type": "string"},
            "recommendation_count": {"type": "integer"},
            "covered_sessions": {"type": "integer"},
            "coverage_rate": {"type": "number"},
            "personalized_rate": {"type": "number"},
            "fallback_rate": {"type": "number"},
            "avg_confidence": {"type": "number"},
            "avg_score": {"type": "number"},
            "freshness_lag_minutes": {"type": "number"},
            "quality_status": {"type": "string"},
            "rollback_ready": {"type": "boolean"},
            "active_snapshot_path": {"type": "string"},
            "previous_snapshot_path": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "RecommendationItem": {
        "type": "object",
        "properties": {
            "user_session": {"type": "string"},
            "user_id": {"type": "string"},
            "rank": {"type": "integer"},
            "product_id": {"type": "string"},
            "brand": {"type": "string"},
            "category_level1": {"type": "string"},
            "score": {"type": "number"},
            "confidence": {"type": "number"},
            "reason_codes": {"type": "array", "items": {"type": "string"}},
            "source": {"type": "string"},
            "fallback_used": {"type": "boolean"},
        },
        "additionalProperties": True,
    },
    "RecommendationQuality": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "recommendation_count": {"type": "integer"},
            "target_sessions": {"type": "integer"},
            "covered_sessions": {"type": "integer"},
            "coverage_rate": {"type": "number"},
            "fallback_rate": {"type": "number"},
            "personalized_rate": {"type": "number"},
            "avg_confidence": {"type": "number"},
            "freshness_lag_minutes": {"type": "number"},
            "duplicate_recommendation_rate": {"type": "number"},
            "invalid_product_rate": {"type": "number"},
            "passed": {"type": "boolean"},
            "checks": {"type": "array"},
        },
        "additionalProperties": True,
    },
    "RecommendationAlert": {
        "type": "object",
        "properties": {
            "severity": {"type": "string"},
            "alert_code": {"type": "string"},
            "metric": {"type": "string"},
            "actual": {"type": "number"},
            "threshold": {"type": "number"},
            "message": {"type": "string"},
            "recommended_action": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "FeatureMartSummary": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "input_snapshot": {"type": "object"},
            "date_range": {"type": "object"},
            "partitions": {"type": "object"},
            "freshness": {"type": "object"},
            "quality_status": {"type": "string"},
            "raw_rows": {"type": "integer"},
            "cleaned_rows": {"type": "integer"},
            "deduped_event_rows": {"type": "integer"},
        },
        "additionalProperties": True,
    },
    "AnomalySummary": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "radar_status": {"type": "string"},
            "alert_count": {"type": "integer"},
            "critical_count": {"type": "integer"},
            "warning_count": {"type": "integer"},
            "watch_count": {"type": "integer"},
            "signal_count": {"type": "integer"},
            "monitored_entities": {"type": "integer"},
            "monitored_days": {"type": "integer"},
            "max_robust_z": {"type": "number"},
            "date_range": {"type": "object"},
            "top_alert": {"type": ["object", "null"]},
        },
        "additionalProperties": True,
    },
    "AnomalyAlert": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "dt": {"type": ["string", "null"]},
            "severity": {"type": "string"},
            "alert_code": {"type": "string"},
            "entity_type": {"type": "string"},
            "entity_id": {"type": "string"},
            "entity_label": {"type": "string"},
            "metric": {"type": "string"},
            "actual": {"type": ["number", "null"]},
            "baseline": {"type": ["number", "null"]},
            "delta": {"type": ["number", "null"]},
            "delta_rate": {"type": ["number", "null"]},
            "robust_z": {"type": ["number", "null"]},
            "direction": {"type": "string"},
            "message": {"type": "string"},
            "recommended_action": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "AnomalyTimelinePoint": {
        "type": "object",
        "properties": {
            "dt": {"type": "string"},
            "signal_count": {"type": "integer"},
            "critical_count": {"type": "integer"},
            "warning_count": {"type": "integer"},
            "watch_count": {"type": "integer"},
            "max_robust_z": {"type": "number"},
        },
        "additionalProperties": True,
    },
    "AnomalyRules": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "baseline": {"type": "string"},
            "rules": {"type": "array", "items": {"type": "object"}},
        },
        "additionalProperties": True,
    },
    "LifecycleSummary": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "snapshot_dt": {"type": ["string", "null"]},
            "user_count": {"type": "integer"},
            "purchase_count": {"type": "integer"},
            "revenue": {"type": "number"},
            "at_risk_users": {"type": "integer"},
            "convert_intent_users": {"type": "integer"},
            "high_value_users": {"type": "integer"},
            "avg_recency_days": {"type": "number"},
            "segment_count": {"type": "integer"},
            "top_segment": {"type": ["object", "null"]},
            "rules": {"type": "object"},
        },
        "additionalProperties": True,
    },
    "LifecycleSegment": {
        "type": "object",
        "properties": {
            "lifecycle_segment": {"type": "string"},
            "users": {"type": "integer"},
            "revenue": {"type": "number"},
            "purchases": {"type": "integer"},
            "avg_recency_days": {"type": "number"},
        },
        "additionalProperties": True,
    },
    "LifecycleUser": {
        "type": "object",
        "properties": {
            "user_id": {"type": "string"},
            "lifecycle_segment": {"type": "string"},
            "risk_band": {"type": "string"},
            "sessions": {"type": "integer"},
            "views": {"type": "integer"},
            "carts": {"type": "integer"},
            "purchases": {"type": "integer"},
            "revenue": {"type": "number"},
            "recency_days": {"type": "integer"},
            "preferred_category_level1": {"type": ["string", "null"]},
            "recommended_action": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "LifecycleCategoryAffinity": {
        "type": "object",
        "properties": {
            "category_level1": {"type": ["string", "null"]},
            "users": {"type": "integer"},
            "user_revenue": {"type": "number"},
            "user_purchases": {"type": "integer"},
            "category_revenue": {"type": ["number", "null"]},
            "category_purchases": {"type": ["integer", "null"]},
        },
        "additionalProperties": True,
    },
    "LifecycleRules": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "model": {"type": "string"},
            "rules": {"type": "array", "items": {"type": "object"}},
        },
        "additionalProperties": True,
    },
    "ExperimentSummary": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "experiment_count": {"type": "integer"},
            "assignment_rows": {"type": "integer"},
            "assigned_users": {"type": "integer"},
            "treatment_assignments": {"type": "integer"},
            "control_assignments": {"type": "integer"},
            "treatment_split": {"type": "number"},
            "expected_incremental_gmv": {"type": "number"},
            "expected_incremental_purchases": {"type": "number"},
            "guardrail_status": {"type": "string"},
            "recommendation_coverage": {"type": "object"},
            "optimization_selected_count": {"type": "integer"},
            "experiments": {"type": "array", "items": {"type": "object"}},
            "causal_caveat": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "ExperimentCatalogItem": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "experiment_key": {"type": "string"},
            "name": {"type": "string"},
            "primary_metric": {"type": "string"},
            "secondary_metric": {"type": "string"},
            "target_rule": {"type": "string"},
            "policy": {"type": "string"},
            "expected_uplift_rate": {"type": "number"},
            "status": {"type": "string"},
            "measurement_window": {"type": "string"},
            "guardrail_metrics": {"type": "array", "items": {"type": "string"}},
        },
        "additionalProperties": True,
    },
    "ExperimentAssignment": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "source_run_id": {"type": "string"},
            "experiment_key": {"type": "string"},
            "name": {"type": "string"},
            "user_id": {"type": "string"},
            "variant": {"type": "string"},
            "assignment_bucket": {"type": "number"},
            "lifecycle_segment": {"type": "string"},
            "risk_band": {"type": "string"},
            "preferred_category_level1": {"type": ["string", "null"]},
            "sessions": {"type": "integer"},
            "views": {"type": "integer"},
            "carts": {"type": "integer"},
            "purchases": {"type": "integer"},
            "revenue": {"type": "number"},
            "expected_incremental_purchase_prob": {"type": "number"},
            "expected_incremental_gmv": {"type": "number"},
            "policy": {"type": "string"},
            "primary_metric": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "ExperimentSegment": {
        "type": "object",
        "properties": {
            "experiment_key": {"type": "string"},
            "lifecycle_segment": {"type": "string"},
            "variant": {"type": "string"},
            "users": {"type": "integer"},
            "observed_revenue": {"type": "number"},
            "observed_purchases": {"type": "integer"},
            "expected_incremental_gmv": {"type": "number"},
            "experiment_users": {"type": "integer"},
            "segment_share": {"type": "number"},
        },
        "additionalProperties": True,
    },
    "ExperimentGuardrails": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "status": {"type": "string"},
            "checks": {"type": "array", "items": {"type": "object"}},
            "segment_imbalance": {"type": "array", "items": {"type": "object"}},
            "recommended_action": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "FeatureMartFreshness": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "generated_at": {"type": "string"},
            "min_event_time": {"type": ["string", "null"]},
            "max_event_time": {"type": ["string", "null"]},
            "watermark_time": {"type": ["string", "null"]},
            "late_rows": {"type": "integer"},
            "late_rate": {"type": "number"},
            "affected_dates": {"type": "array", "items": {"type": "string"}},
            "freshness_lag_hours": {"type": ["number", "null"]},
            "max_freshness_lag_hours": {"type": "number"},
            "sla_status": {"type": "string"},
        },
        "additionalProperties": True,
    },
    "FeatureMartQuality": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "raw_rows": {"type": "integer"},
            "cleaned_rows": {"type": "integer"},
            "deduped_event_rows": {"type": "integer"},
            "duplicate_event_keys": {"type": "integer"},
            "duplicate_event_key_rate": {"type": "number"},
            "invalid_event_type_rows": {"type": "integer"},
            "missing_user_rows": {"type": "integer"},
            "missing_product_rows": {"type": "integer"},
            "purchase_missing_or_invalid_price_rows": {"type": "integer"},
            "null_session_rows": {"type": "integer"},
            "quarantined_rows": {"type": "integer"},
            "quarantined_rate": {"type": "number"},
            "quality_status": {"type": "string"},
            "checks": {"type": "array"},
        },
        "additionalProperties": True,
    },
    "FeatureMartPartitionReport": {
        "type": "object",
        "properties": {
            "contract_version": {"type": "string"},
            "run_id": {"type": "string"},
            "expected": {"type": "integer"},
            "written": {"type": "integer"},
            "missing": {"type": "array", "items": {"type": "string"}},
            "min_dt": {"type": ["string", "null"]},
            "max_dt": {"type": ["string", "null"]},
            "partitions": {"type": "array", "items": {"type": "object"}},
        },
        "additionalProperties": True,
    },
    "FeatureMartProduct": {
        "type": "object",
        "properties": {
            "dt": {"type": "string"},
            "product_id": {"type": "string"},
            "brand": {"type": "string"},
            "category_level1": {"type": "string"},
            "views": {"type": "integer"},
            "carts": {"type": "integer"},
            "purchases": {"type": "integer"},
            "unique_users": {"type": "integer"},
            "unique_sessions": {"type": "integer"},
            "revenue": {"type": "number"},
            "avg_price": {"type": ["number", "null"]},
            "view_to_cart_rate": {"type": ["number", "null"]},
            "cart_to_purchase_rate": {"type": ["number", "null"]},
            "view_to_purchase_rate": {"type": ["number", "null"]},
        },
        "additionalProperties": True,
    },
    "FeatureMartCategory": {
        "type": "object",
        "properties": {
            "dt": {"type": "string"},
            "category_level1": {"type": "string"},
            "views": {"type": "integer"},
            "carts": {"type": "integer"},
            "purchases": {"type": "integer"},
            "unique_users": {"type": "integer"},
            "revenue": {"type": "number"},
            "avg_price": {"type": ["number", "null"]},
            "conversion_rate": {"type": ["number", "null"]},
        },
        "additionalProperties": True,
    },
    "FeatureMartUser": {
        "type": "object",
        "properties": {
            "dt": {"type": "string"},
            "user_id": {"type": "string"},
            "sessions": {"type": "integer"},
            "views": {"type": "integer"},
            "carts": {"type": "integer"},
            "purchases": {"type": "integer"},
            "revenue": {"type": "number"},
            "active_minutes": {"type": ["number", "null"]},
            "distinct_products": {"type": "integer"},
            "distinct_categories": {"type": "integer"},
            "preferred_category_level1": {"type": ["string", "null"]},
        },
        "additionalProperties": True,
    },
    "TableRow": {
        "type": "object",
        "required": [
            "event_time",
            "event_type",
            "product_id",
            "category_id",
            "category_code",
            "brand",
            "price",
            "user_id",
            "user_session",
        ],
        "properties": {
            "event_time": {"type": "string"},
            "event_type": {"type": "string"},
            "product_id": {"type": "string"},
            "category_id": {"type": "string"},
            "category_code": {"type": "string"},
            "brand": {"type": "string"},
            "price": {"type": "string"},
            "user_id": {"type": "string"},
            "user_session": {"type": "string"},
        },
    },
    "TableResult": {
        "type": "object",
        "required": ["page", "size", "total", "rows"],
        "properties": {
            "page": {"type": "integer"},
            "size": {"type": "integer"},
            "total": {"type": "integer"},
            "rows": {"type": "array", "items": {"$ref": "#/components/schemas/TableRow"}},
        },
    },
    "JobStatus": {
        "type": "object",
        "properties": {
            "job_id": {"type": "string"},
            "job_type": {"type": "string"},
            "status": {"type": "string"},
            "config_path": {"type": "string"},
            "created_at": {"type": "string"},
            "started_at": {"type": ["string", "null"]},
            "finished_at": {"type": ["string", "null"]},
            "message": {"type": "string"},
            "error": {"type": ["string", "null"]},
            "elapsed_seconds": {"type": "number"},
            "input_path": {"type": "string"},
            "storage_mode": {"type": "string"},
            "run_id": {"type": ["string", "null"]},
            "contract_version": {"type": ["string", "null"]},
            "config_hash": {"type": ["string", "null"]},
            "spark_application_id": {"type": ["string", "null"]},
            "spark_application_status": {"type": ["string", "null"]},
            "spark_history_metrics_status": {"type": ["string", "null"]},
            "spark_history_metrics_error": {"type": ["string", "null"]},
            "spark_history_metrics": {"type": ["object", "null"]},
            "input_snapshot": {"type": ["object", "null"]},
            "quality_status": {"type": ["string", "null"]},
            "quality_report": {"type": ["object", "null"]},
            "output_artifacts": {"type": ["object", "null"]},
            "failure_stage": {"type": ["string", "null"]},
        },
        "additionalProperties": True,
    },
    "JobLineage": {
        "type": "object",
        "properties": {
            "job_id": {"type": "string"},
            "run_id": {"type": ["string", "null"]},
            "contract_version": {"type": ["string", "null"]},
            "config_hash": {"type": ["string", "null"]},
            "spark_application_id": {"type": ["string", "null"]},
            "spark_application_status": {"type": ["string", "null"]},
            "spark_history_metrics_status": {"type": ["string", "null"]},
            "spark_history_metrics_error": {"type": ["string", "null"]},
            "spark_history_metrics": {"type": ["object", "null"]},
            "input_snapshot": {"type": ["object", "null"]},
            "output_artifacts": {"type": ["object", "null"]},
        },
    },
    "JobQuality": {
        "type": "object",
        "properties": {
            "job_id": {"type": "string"},
            "run_id": {"type": ["string", "null"]},
            "spark_application_id": {"type": ["string", "null"]},
            "spark_application_status": {"type": ["string", "null"]},
            "spark_history_metrics_status": {"type": ["string", "null"]},
            "spark_history_metrics_error": {"type": ["string", "null"]},
            "spark_history_metrics": {"type": ["object", "null"]},
            "quality_status": {"type": ["string", "null"]},
            "quality_report": {"type": ["object", "null"]},
            "failure_stage": {"type": ["string", "null"]},
        },
    },
    "JobList": {
        "type": "object",
        "required": ["total", "rows"],
        "properties": {
            "total": {"type": "integer"},
            "rows": {"type": "array", "items": {"$ref": "#/components/schemas/JobStatus"}},
        },
    },
    "HealthStatus": {
        "type": "object",
        "required": ["status"],
        "properties": {"status": {"type": "string"}},
        "additionalProperties": True,
    },
    "ErrorEnvelope": {
        "allOf": [
            {"$ref": "#/components/schemas/ApiEnvelope"},
            {
                "type": "object",
                "properties": {
                    "code": {"type": "integer", "minimum": 1},
                    "data": {"type": "null"},
                },
            },
        ]
    },
}


ENDPOINTS: list[dict[str, Any]] = [
    {"method": "GET", "path": "/healthz", "response_schema": "ApiEnvelope<HealthStatus>"},
    {"method": "GET", "path": "/readyz", "response_schema": "ApiEnvelope<HealthStatus>"},
    {"method": "GET", "path": "/api/v1/health", "response_schema": "ApiEnvelope<HealthStatus>"},
    {"method": "GET", "path": "/api/v1/contracts", "response_schema": "ApiEnvelope<ApiContract>"},
    {"method": "GET", "path": "/api/v1/openapi.json", "response_schema": "OpenAPI 3.1"},
    {"method": "GET", "path": "/api/v1/summary", "response_schema": "ApiEnvelope<Summary>"},
    {"method": "GET", "path": "/api/v1/events/distribution", "response_schema": "ApiEnvelope<NamedValue[]>"},
    {"method": "GET", "path": "/api/v1/trend/daily-events", "response_schema": "ApiEnvelope<DateValue[]>"},
    {"method": "GET", "path": "/api/v1/trend/daily-sales", "response_schema": "ApiEnvelope<DateValue[]>"},
    {"method": "GET", "path": "/api/v1/ranking/categories", "response_schema": "ApiEnvelope<NamedValue[]>"},
    {"method": "GET", "path": "/api/v1/ranking/brands", "response_schema": "ApiEnvelope<NamedValue[]>"},
    {"method": "GET", "path": "/api/v1/conversion/funnel", "response_schema": "ApiEnvelope<SessionFunnel>"},
    {"method": "GET", "path": "/api/v1/conversion/daily", "response_schema": "ApiEnvelope<DailyConversion[]>"},
    {
        "method": "GET",
        "path": "/api/v1/conversion/products",
        "query": {"limit": {"type": "integer", "default": 20, "minimum": 1, "maximum": 100}},
        "response_schema": "ApiEnvelope<ProductConversion[]>",
    },
    {"method": "GET", "path": "/api/v1/journey/summary", "response_schema": "ApiEnvelope<JourneySummary>"},
    {
        "method": "GET",
        "path": "/api/v1/journey/paths",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<JourneyPath[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/journey/transitions",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<JourneyTransition[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/journey/exit-events",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<JourneyExitEvent[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/journey/purchase-paths",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<JourneyPurchasePath[]>",
    },
    {"method": "GET", "path": "/api/v1/forecasting/summary", "response_schema": "ApiEnvelope<ForecastingSummary>"},
    {
        "method": "GET",
        "path": "/api/v1/forecasting/series",
        "query": {"scope": {"type": "string", "required": False}, "entity": {"type": "string", "required": False}, "metric": {"type": "string", "required": False}},
        "response_schema": "ApiEnvelope<ForecastingSeriesPoint[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/forecasting/entities",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<ForecastingEntity[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/forecasting/backtest",
        "query": {"scope": {"type": "string", "required": False}, "entity": {"type": "string", "required": False}},
        "response_schema": "ApiEnvelope<ForecastingBacktestPoint[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/forecasting/risks",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}, "severity": {"type": "string", "required": False}},
        "response_schema": "ApiEnvelope<ForecastingRisk[]>",
    },
    {"method": "GET", "path": "/api/v1/forecasting/quality", "response_schema": "ApiEnvelope<ForecastingQuality>"},
    {"method": "GET", "path": "/api/v1/affinity/summary", "response_schema": "ApiEnvelope<AffinitySummary>"},
    {
        "method": "GET",
        "path": "/api/v1/affinity/nodes",
        "query": {
            "entity_type": {"type": "string", "required": False},
            "q": {"type": "string", "required": False},
            "limit": {"type": "integer", "default": 100, "minimum": 1, "maximum": 300},
        },
        "response_schema": "ApiEnvelope<AffinityNode[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/affinity/edges",
        "query": {
            "entity_id": {"type": "string", "required": False},
            "relation_type": {"type": "string", "required": False},
            "limit": {"type": "integer", "default": 100, "minimum": 1, "maximum": 300},
        },
        "response_schema": "ApiEnvelope<AffinityEdge[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/affinity/communities",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<AffinityCommunity[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/affinity/opportunities",
        "query": {
            "type": {"type": "string", "required": False},
            "confidence": {"type": "number", "required": False},
            "limit": {"type": "integer", "default": 100, "minimum": 1, "maximum": 300},
        },
        "response_schema": "ApiEnvelope<AffinityOpportunity[]>",
    },
    {"method": "GET", "path": "/api/v1/affinity/quality", "response_schema": "ApiEnvelope<AffinityQuality>"},
    {"method": "GET", "path": "/api/v1/cohorts/summary", "response_schema": "ApiEnvelope<CohortSummary>"},
    {
        "method": "GET",
        "path": "/api/v1/cohorts/retention",
        "query": {
            "cohort": {"type": "string", "required": False},
            "metric": {"type": "string", "required": False},
        },
        "response_schema": "ApiEnvelope<CohortRetentionCell[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/cohorts/value-curves",
        "query": {"cohort": {"type": "string", "required": False}},
        "response_schema": "ApiEnvelope<CohortValueCurve[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/cohorts/repurchase-intervals",
        "response_schema": "ApiEnvelope<CohortRepurchaseInterval[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/cohorts/segments",
        "query": {
            "category": {"type": "string", "required": False},
            "limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200},
        },
        "response_schema": "ApiEnvelope<CohortSegment[]>",
    },
    {"method": "GET", "path": "/api/v1/cohorts/quality", "response_schema": "ApiEnvelope<CohortQuality>"},
    {"method": "GET", "path": "/api/v1/portfolio/summary", "response_schema": "ApiEnvelope<PortfolioSummary>"},
    {
        "method": "GET",
        "path": "/api/v1/portfolio/categories",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<PortfolioCategoryMix[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/portfolio/brands",
        "query": {
            "category": {"type": "string", "required": False},
            "limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200},
        },
        "response_schema": "ApiEnvelope<PortfolioBrandMix[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/portfolio/price-bands",
        "query": {
            "category": {"type": "string", "required": False},
            "price_band": {"type": "string", "required": False},
        },
        "response_schema": "ApiEnvelope<PortfolioPriceBand[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/portfolio/products",
        "query": {
            "category": {"type": "string", "required": False},
            "brand": {"type": "string", "required": False},
            "limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200},
        },
        "response_schema": "ApiEnvelope<PortfolioProductConcentration[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/portfolio/concentration",
        "response_schema": "ApiEnvelope<PortfolioProductConcentration[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/portfolio/opportunities",
        "query": {
            "type": {"type": "string", "required": False},
            "confidence": {"type": "number", "required": False},
            "limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200},
        },
        "response_schema": "ApiEnvelope<PortfolioOpportunity[]>",
    },
    {"method": "GET", "path": "/api/v1/portfolio/quality", "response_schema": "ApiEnvelope<PortfolioQuality>"},
    {"method": "GET", "path": "/api/v1/cart-recovery/summary", "response_schema": "ApiEnvelope<CartSummary>"},
    {
        "method": "GET",
        "path": "/api/v1/cart-recovery/categories",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<CartCategorySegment[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/cart-recovery/products",
        "query": {
            "category": {"type": "string", "required": False},
            "brand": {"type": "string", "required": False},
            "limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200},
        },
        "response_schema": "ApiEnvelope<CartProductSegment[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/cart-recovery/recovery-queue",
        "query": {
            "action": {"type": "string", "required": False},
            "confidence": {"type": "number", "required": False},
            "limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200},
        },
        "response_schema": "ApiEnvelope<CartRecoveryQueueItem[]>",
    },
    {"method": "GET", "path": "/api/v1/cart-recovery/quality", "response_schema": "ApiEnvelope<CartQuality>"},
    {"method": "GET", "path": "/api/v1/attribution/summary", "response_schema": "ApiEnvelope<AttributionSummary>"},
    {
        "method": "GET",
        "path": "/api/v1/attribution/models",
        "query": {"entity_type": {"type": "string", "required": False}},
        "response_schema": "ApiEnvelope<AttributionModel[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/attribution/entities",
        "query": {
            "entity_type": {"type": "string", "required": False},
            "model": {"type": "string", "default": "time_decay"},
            "limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200},
        },
        "response_schema": "ApiEnvelope<AttributionEntity[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/attribution/paths",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<AttributionPath[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/attribution/assists",
        "query": {
            "entity_type": {"type": "string", "required": False},
            "limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200},
        },
        "response_schema": "ApiEnvelope<AttributionAssist[]>",
    },
    {"method": "GET", "path": "/api/v1/attribution/quality", "response_schema": "ApiEnvelope<AttributionQuality>"},
    {"method": "GET", "path": "/api/v1/optimization/summary", "response_schema": "ApiEnvelope<OptimizationSummary>"},
    {
        "method": "GET",
        "path": "/api/v1/optimization/plan",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 100}},
        "response_schema": "ApiEnvelope<OptimizationPlanItem[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/optimization/candidates",
        "query": {"limit": {"type": "integer", "default": 100, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<OptimizationCandidate[]>",
    },
    {"method": "GET", "path": "/api/v1/optimization/quality", "response_schema": "ApiEnvelope<OptimizationQuality>"},
    {"method": "GET", "path": "/api/v1/recommendations/summary", "response_schema": "ApiEnvelope<RecommendationSummary>"},
    {
        "method": "GET",
        "path": "/api/v1/recommendations/items",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<RecommendationItem[]>",
    },
    {"method": "GET", "path": "/api/v1/recommendations/quality", "response_schema": "ApiEnvelope<RecommendationQuality>"},
    {"method": "GET", "path": "/api/v1/recommendations/alerts", "response_schema": "ApiEnvelope<RecommendationAlert[]>"},
    {"method": "GET", "path": "/api/v1/anomalies/summary", "response_schema": "ApiEnvelope<AnomalySummary>"},
    {
        "method": "GET",
        "path": "/api/v1/anomalies/alerts",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<AnomalyAlert[]>",
    },
    {"method": "GET", "path": "/api/v1/anomalies/timeline", "response_schema": "ApiEnvelope<AnomalyTimelinePoint[]>"},
    {"method": "GET", "path": "/api/v1/anomalies/rules", "response_schema": "ApiEnvelope<AnomalyRules>"},
    {"method": "GET", "path": "/api/v1/lifecycle/summary", "response_schema": "ApiEnvelope<LifecycleSummary>"},
    {"method": "GET", "path": "/api/v1/lifecycle/segments", "response_schema": "ApiEnvelope<LifecycleSegment[]>"},
    {
        "method": "GET",
        "path": "/api/v1/lifecycle/risk-queue",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<LifecycleUser[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/lifecycle/category-affinity",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<LifecycleCategoryAffinity[]>",
    },
    {"method": "GET", "path": "/api/v1/lifecycle/rules", "response_schema": "ApiEnvelope<LifecycleRules>"},
    {"method": "GET", "path": "/api/v1/experiments/summary", "response_schema": "ApiEnvelope<ExperimentSummary>"},
    {"method": "GET", "path": "/api/v1/experiments/catalog", "response_schema": "ApiEnvelope<ExperimentCatalogItem[]>"},
    {
        "method": "GET",
        "path": "/api/v1/experiments/assignments",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<ExperimentAssignment[]>",
    },
    {"method": "GET", "path": "/api/v1/experiments/segments", "response_schema": "ApiEnvelope<ExperimentSegment[]>"},
    {"method": "GET", "path": "/api/v1/experiments/guardrails", "response_schema": "ApiEnvelope<ExperimentGuardrails>"},
    {"method": "GET", "path": "/api/v1/feature-mart/summary", "response_schema": "ApiEnvelope<FeatureMartSummary>"},
    {"method": "GET", "path": "/api/v1/feature-mart/freshness", "response_schema": "ApiEnvelope<FeatureMartFreshness>"},
    {"method": "GET", "path": "/api/v1/feature-mart/quality", "response_schema": "ApiEnvelope<FeatureMartQuality>"},
    {"method": "GET", "path": "/api/v1/feature-mart/partitions", "response_schema": "ApiEnvelope<FeatureMartPartitionReport>"},
    {
        "method": "GET",
        "path": "/api/v1/feature-mart/products",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<FeatureMartProduct[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/feature-mart/categories",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<FeatureMartCategory[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/feature-mart/users",
        "query": {"limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 200}},
        "response_schema": "ApiEnvelope<FeatureMartUser[]>",
    },
    {
        "method": "GET",
        "path": "/api/v1/table",
        "query": {
            "page": {"type": "integer", "default": 1, "minimum": 1},
            "size": {"type": "integer", "default": 20, "minimum": 1, "maximum": 100},
            "event_type": {"type": "string", "required": False},
            "brand": {"type": "string", "required": False},
        },
        "response_schema": "ApiEnvelope<TableResult>",
    },
    {"method": "GET", "path": "/api/v1/job", "response_schema": "ApiEnvelope<JobStatus>"},
    {"method": "GET", "path": "/api/v1/jobs", "response_schema": "ApiEnvelope<JobList>"},
    {"method": "POST", "path": "/api/v1/jobs", "response_schema": "ApiEnvelope<JobStatus>", "status": 202},
    {"method": "GET", "path": "/api/v1/jobs/{job_id}", "response_schema": "ApiEnvelope<JobStatus>"},
    {"method": "GET", "path": "/api/v1/jobs/{job_id}/lineage", "response_schema": "ApiEnvelope<JobLineage>"},
    {"method": "GET", "path": "/api/v1/jobs/{job_id}/quality", "response_schema": "ApiEnvelope<JobQuality>"},
    {"method": "POST", "path": "/api/v1/refresh", "response_schema": "ApiEnvelope<{status:string,job_id:string}>", "status": 202},
]


def build_contract() -> dict[str, Any]:
    return {
        "version": "v1",
        "base_path": "/api/v1",
        "envelope": "ApiEnvelope",
        "endpoints": ENDPOINTS,
        "schemas": API_SCHEMAS,
        "error_codes": {
            "40001": "invalid request parameter",
            "40401": "resource not found",
            "40901": "spark refresh job already running",
            "50301": "metric cache or raw data is not ready",
            "50001": "internal server error",
        },
    }


def envelope_schema(schema: dict[str, Any] | None = None) -> dict[str, Any]:
    result = dict(API_SCHEMAS["ApiEnvelope"])
    properties = dict(result["properties"])
    properties["data"] = schema or {}
    result["properties"] = properties
    return result


def build_openapi() -> dict[str, Any]:
    array_named_value = {"type": "array", "items": {"$ref": "#/components/schemas/NamedValue"}}
    array_date_value = {"type": "array", "items": {"$ref": "#/components/schemas/DateValue"}}
    array_daily_conversion = {"type": "array", "items": {"$ref": "#/components/schemas/DailyConversion"}}
    array_product_conversion = {"type": "array", "items": {"$ref": "#/components/schemas/ProductConversion"}}
    array_journey_path = {"type": "array", "items": {"$ref": "#/components/schemas/JourneyPath"}}
    array_journey_transition = {"type": "array", "items": {"$ref": "#/components/schemas/JourneyTransition"}}
    array_journey_exit_event = {"type": "array", "items": {"$ref": "#/components/schemas/JourneyExitEvent"}}
    array_journey_purchase_path = {"type": "array", "items": {"$ref": "#/components/schemas/JourneyPurchasePath"}}
    array_forecasting_series = {"type": "array", "items": {"$ref": "#/components/schemas/ForecastingSeriesPoint"}}
    array_forecasting_entity = {"type": "array", "items": {"$ref": "#/components/schemas/ForecastingEntity"}}
    array_forecasting_backtest = {"type": "array", "items": {"$ref": "#/components/schemas/ForecastingBacktestPoint"}}
    array_forecasting_risk = {"type": "array", "items": {"$ref": "#/components/schemas/ForecastingRisk"}}
    array_affinity_node = {"type": "array", "items": {"$ref": "#/components/schemas/AffinityNode"}}
    array_affinity_edge = {"type": "array", "items": {"$ref": "#/components/schemas/AffinityEdge"}}
    array_affinity_community = {"type": "array", "items": {"$ref": "#/components/schemas/AffinityCommunity"}}
    array_affinity_opportunity = {"type": "array", "items": {"$ref": "#/components/schemas/AffinityOpportunity"}}
    array_cohort_retention = {"type": "array", "items": {"$ref": "#/components/schemas/CohortRetentionCell"}}
    array_cohort_interval = {"type": "array", "items": {"$ref": "#/components/schemas/CohortRepurchaseInterval"}}
    array_cohort_value = {"type": "array", "items": {"$ref": "#/components/schemas/CohortValueCurve"}}
    array_cohort_segment = {"type": "array", "items": {"$ref": "#/components/schemas/CohortSegment"}}
    array_portfolio_category = {"type": "array", "items": {"$ref": "#/components/schemas/PortfolioCategoryMix"}}
    array_portfolio_brand = {"type": "array", "items": {"$ref": "#/components/schemas/PortfolioBrandMix"}}
    array_portfolio_band = {"type": "array", "items": {"$ref": "#/components/schemas/PortfolioPriceBand"}}
    array_portfolio_product = {"type": "array", "items": {"$ref": "#/components/schemas/PortfolioProductConcentration"}}
    array_portfolio_opportunity = {"type": "array", "items": {"$ref": "#/components/schemas/PortfolioOpportunity"}}
    array_cart_category = {"type": "array", "items": {"$ref": "#/components/schemas/CartCategorySegment"}}
    array_cart_product = {"type": "array", "items": {"$ref": "#/components/schemas/CartProductSegment"}}
    array_cart_queue = {"type": "array", "items": {"$ref": "#/components/schemas/CartRecoveryQueueItem"}}
    array_attribution_model = {"type": "array", "items": {"$ref": "#/components/schemas/AttributionModel"}}
    array_attribution_entity = {"type": "array", "items": {"$ref": "#/components/schemas/AttributionEntity"}}
    array_attribution_path = {"type": "array", "items": {"$ref": "#/components/schemas/AttributionPath"}}
    array_attribution_assist = {"type": "array", "items": {"$ref": "#/components/schemas/AttributionAssist"}}
    array_optimization_plan = {"type": "array", "items": {"$ref": "#/components/schemas/OptimizationPlanItem"}}
    array_optimization_candidate = {"type": "array", "items": {"$ref": "#/components/schemas/OptimizationCandidate"}}
    array_recommendation_item = {"type": "array", "items": {"$ref": "#/components/schemas/RecommendationItem"}}
    array_recommendation_alert = {"type": "array", "items": {"$ref": "#/components/schemas/RecommendationAlert"}}
    array_anomaly_alert = {"type": "array", "items": {"$ref": "#/components/schemas/AnomalyAlert"}}
    array_anomaly_timeline = {"type": "array", "items": {"$ref": "#/components/schemas/AnomalyTimelinePoint"}}
    array_lifecycle_segment = {"type": "array", "items": {"$ref": "#/components/schemas/LifecycleSegment"}}
    array_lifecycle_user = {"type": "array", "items": {"$ref": "#/components/schemas/LifecycleUser"}}
    array_lifecycle_category_affinity = {
        "type": "array",
        "items": {"$ref": "#/components/schemas/LifecycleCategoryAffinity"},
    }
    array_experiment_catalog = {"type": "array", "items": {"$ref": "#/components/schemas/ExperimentCatalogItem"}}
    array_experiment_assignment = {"type": "array", "items": {"$ref": "#/components/schemas/ExperimentAssignment"}}
    array_experiment_segment = {"type": "array", "items": {"$ref": "#/components/schemas/ExperimentSegment"}}
    array_feature_mart_product = {"type": "array", "items": {"$ref": "#/components/schemas/FeatureMartProduct"}}
    array_feature_mart_category = {"type": "array", "items": {"$ref": "#/components/schemas/FeatureMartCategory"}}
    array_feature_mart_user = {"type": "array", "items": {"$ref": "#/components/schemas/FeatureMartUser"}}
    return {
        "openapi": "3.1.0",
        "info": {
            "title": "Enormous Data Analytics API",
            "version": "1.0.0",
            "description": "Spark powered ecommerce behavior analytics API.",
        },
        "paths": {
            "/api/v1/summary": _get_response(envelope_schema({"$ref": "#/components/schemas/Summary"})),
            "/api/v1/events/distribution": _get_response(envelope_schema(array_named_value)),
            "/api/v1/trend/daily-events": _get_response(envelope_schema(array_date_value)),
            "/api/v1/trend/daily-sales": _get_response(envelope_schema(array_date_value)),
            "/api/v1/ranking/categories": _get_response(envelope_schema(array_named_value)),
            "/api/v1/ranking/brands": _get_response(envelope_schema(array_named_value)),
            "/api/v1/conversion/funnel": _get_response(
                envelope_schema({"$ref": "#/components/schemas/SessionFunnel"})
            ),
            "/api/v1/conversion/daily": _get_response(envelope_schema(array_daily_conversion)),
            "/api/v1/conversion/products": _get_response(envelope_schema(array_product_conversion)),
            "/api/v1/journey/summary": _get_response(
                envelope_schema({"$ref": "#/components/schemas/JourneySummary"})
            ),
            "/api/v1/journey/paths": _get_response(envelope_schema(array_journey_path)),
            "/api/v1/journey/transitions": _get_response(envelope_schema(array_journey_transition)),
            "/api/v1/journey/exit-events": _get_response(envelope_schema(array_journey_exit_event)),
            "/api/v1/journey/purchase-paths": _get_response(envelope_schema(array_journey_purchase_path)),
            "/api/v1/forecasting/summary": _get_response(
                envelope_schema({"$ref": "#/components/schemas/ForecastingSummary"})
            ),
            "/api/v1/forecasting/series": _get_response(envelope_schema(array_forecasting_series)),
            "/api/v1/forecasting/entities": _get_response(envelope_schema(array_forecasting_entity)),
            "/api/v1/forecasting/backtest": _get_response(envelope_schema(array_forecasting_backtest)),
            "/api/v1/forecasting/risks": _get_response(envelope_schema(array_forecasting_risk)),
            "/api/v1/forecasting/quality": _get_response(
                envelope_schema({"$ref": "#/components/schemas/ForecastingQuality"})
            ),
            "/api/v1/affinity/summary": _get_response(
                envelope_schema({"$ref": "#/components/schemas/AffinitySummary"})
            ),
            "/api/v1/affinity/nodes": _get_response(envelope_schema(array_affinity_node)),
            "/api/v1/affinity/edges": _get_response(envelope_schema(array_affinity_edge)),
            "/api/v1/affinity/communities": _get_response(envelope_schema(array_affinity_community)),
            "/api/v1/affinity/opportunities": _get_response(envelope_schema(array_affinity_opportunity)),
            "/api/v1/affinity/quality": _get_response(
                envelope_schema({"$ref": "#/components/schemas/AffinityQuality"})
            ),
            "/api/v1/cohorts/summary": _get_response(
                envelope_schema({"$ref": "#/components/schemas/CohortSummary"})
            ),
            "/api/v1/cohorts/retention": _get_response(envelope_schema(array_cohort_retention)),
            "/api/v1/cohorts/value-curves": _get_response(envelope_schema(array_cohort_value)),
            "/api/v1/cohorts/repurchase-intervals": _get_response(envelope_schema(array_cohort_interval)),
            "/api/v1/cohorts/segments": _get_response(envelope_schema(array_cohort_segment)),
            "/api/v1/cohorts/quality": _get_response(
                envelope_schema({"$ref": "#/components/schemas/CohortQuality"})
            ),
            "/api/v1/portfolio/summary": _get_response(
                envelope_schema({"$ref": "#/components/schemas/PortfolioSummary"})
            ),
            "/api/v1/portfolio/categories": _get_response(envelope_schema(array_portfolio_category)),
            "/api/v1/portfolio/brands": _get_response(envelope_schema(array_portfolio_brand)),
            "/api/v1/portfolio/price-bands": _get_response(envelope_schema(array_portfolio_band)),
            "/api/v1/portfolio/products": _get_response(envelope_schema(array_portfolio_product)),
            "/api/v1/portfolio/concentration": _get_response(envelope_schema(array_portfolio_product)),
            "/api/v1/portfolio/opportunities": _get_response(envelope_schema(array_portfolio_opportunity)),
            "/api/v1/portfolio/quality": _get_response(
                envelope_schema({"$ref": "#/components/schemas/PortfolioQuality"})
            ),
            "/api/v1/cart-recovery/summary": _get_response(
                envelope_schema({"$ref": "#/components/schemas/CartSummary"})
            ),
            "/api/v1/cart-recovery/categories": _get_response(envelope_schema(array_cart_category)),
            "/api/v1/cart-recovery/products": _get_response(envelope_schema(array_cart_product)),
            "/api/v1/cart-recovery/recovery-queue": _get_response(envelope_schema(array_cart_queue)),
            "/api/v1/cart-recovery/quality": _get_response(
                envelope_schema({"$ref": "#/components/schemas/CartQuality"})
            ),
            "/api/v1/attribution/summary": _get_response(
                envelope_schema({"$ref": "#/components/schemas/AttributionSummary"})
            ),
            "/api/v1/attribution/models": _get_response(envelope_schema(array_attribution_model)),
            "/api/v1/attribution/entities": _get_response(envelope_schema(array_attribution_entity)),
            "/api/v1/attribution/paths": _get_response(envelope_schema(array_attribution_path)),
            "/api/v1/attribution/assists": _get_response(envelope_schema(array_attribution_assist)),
            "/api/v1/attribution/quality": _get_response(
                envelope_schema({"$ref": "#/components/schemas/AttributionQuality"})
            ),
            "/api/v1/optimization/summary": _get_response(
                envelope_schema({"$ref": "#/components/schemas/OptimizationSummary"})
            ),
            "/api/v1/optimization/plan": _get_response(envelope_schema(array_optimization_plan)),
            "/api/v1/optimization/candidates": _get_response(envelope_schema(array_optimization_candidate)),
            "/api/v1/optimization/quality": _get_response(
                envelope_schema({"$ref": "#/components/schemas/OptimizationQuality"})
            ),
            "/api/v1/recommendations/summary": _get_response(
                envelope_schema({"$ref": "#/components/schemas/RecommendationSummary"})
            ),
            "/api/v1/recommendations/items": _get_response(envelope_schema(array_recommendation_item)),
            "/api/v1/recommendations/quality": _get_response(
                envelope_schema({"$ref": "#/components/schemas/RecommendationQuality"})
            ),
            "/api/v1/recommendations/alerts": _get_response(envelope_schema(array_recommendation_alert)),
            "/api/v1/anomalies/summary": _get_response(
                envelope_schema({"$ref": "#/components/schemas/AnomalySummary"})
            ),
            "/api/v1/anomalies/alerts": _get_response(envelope_schema(array_anomaly_alert)),
            "/api/v1/anomalies/timeline": _get_response(envelope_schema(array_anomaly_timeline)),
            "/api/v1/anomalies/rules": _get_response(
                envelope_schema({"$ref": "#/components/schemas/AnomalyRules"})
            ),
            "/api/v1/lifecycle/summary": _get_response(
                envelope_schema({"$ref": "#/components/schemas/LifecycleSummary"})
            ),
            "/api/v1/lifecycle/segments": _get_response(envelope_schema(array_lifecycle_segment)),
            "/api/v1/lifecycle/risk-queue": _get_response(envelope_schema(array_lifecycle_user)),
            "/api/v1/lifecycle/category-affinity": _get_response(envelope_schema(array_lifecycle_category_affinity)),
            "/api/v1/lifecycle/rules": _get_response(
                envelope_schema({"$ref": "#/components/schemas/LifecycleRules"})
            ),
            "/api/v1/experiments/summary": _get_response(
                envelope_schema({"$ref": "#/components/schemas/ExperimentSummary"})
            ),
            "/api/v1/experiments/catalog": _get_response(envelope_schema(array_experiment_catalog)),
            "/api/v1/experiments/assignments": _get_response(envelope_schema(array_experiment_assignment)),
            "/api/v1/experiments/segments": _get_response(envelope_schema(array_experiment_segment)),
            "/api/v1/experiments/guardrails": _get_response(
                envelope_schema({"$ref": "#/components/schemas/ExperimentGuardrails"})
            ),
            "/api/v1/feature-mart/summary": _get_response(
                envelope_schema({"$ref": "#/components/schemas/FeatureMartSummary"})
            ),
            "/api/v1/feature-mart/freshness": _get_response(
                envelope_schema({"$ref": "#/components/schemas/FeatureMartFreshness"})
            ),
            "/api/v1/feature-mart/quality": _get_response(
                envelope_schema({"$ref": "#/components/schemas/FeatureMartQuality"})
            ),
            "/api/v1/feature-mart/partitions": _get_response(
                envelope_schema({"$ref": "#/components/schemas/FeatureMartPartitionReport"})
            ),
            "/api/v1/feature-mart/products": _get_response(envelope_schema(array_feature_mart_product)),
            "/api/v1/feature-mart/categories": _get_response(envelope_schema(array_feature_mart_category)),
            "/api/v1/feature-mart/users": _get_response(envelope_schema(array_feature_mart_user)),
            "/api/v1/job": _get_response(envelope_schema({"$ref": "#/components/schemas/JobStatus"})),
            "/api/v1/jobs": _get_post_response(
                get_schema=envelope_schema({"$ref": "#/components/schemas/JobList"}),
                post_schema=envelope_schema({"$ref": "#/components/schemas/JobStatus"}),
            ),
            "/api/v1/jobs/{job_id}": _get_response(envelope_schema({"$ref": "#/components/schemas/JobStatus"})),
            "/api/v1/jobs/{job_id}/lineage": _get_response(
                envelope_schema({"$ref": "#/components/schemas/JobLineage"})
            ),
            "/api/v1/jobs/{job_id}/quality": _get_response(
                envelope_schema({"$ref": "#/components/schemas/JobQuality"})
            ),
            "/api/v1/table": _get_response(envelope_schema({"$ref": "#/components/schemas/TableResult"})),
            "/api/v1/refresh": _post_response(
                envelope_schema(
                    {
                        "type": "object",
                        "properties": {"status": {"type": "string"}, "job_id": {"type": "string"}},
                    }
                )
            ),
            "/api/v1/contracts": _get_response(envelope_schema({"type": "object"})),
            "/api/v1/openapi.json": _get_response({"type": "object"}),
            "/healthz": _get_response(envelope_schema({"$ref": "#/components/schemas/HealthStatus"})),
            "/readyz": _get_response(envelope_schema({"$ref": "#/components/schemas/HealthStatus"})),
        },
        "components": {"schemas": API_SCHEMAS},
    }


def _get_response(schema: dict[str, Any]) -> dict[str, Any]:
    return {"get": {"responses": {"200": _json_response(schema), "default": _json_response(API_SCHEMAS["ErrorEnvelope"])}}}


def _post_response(schema: dict[str, Any]) -> dict[str, Any]:
    return {"post": {"responses": {"202": _json_response(schema), "default": _json_response(API_SCHEMAS["ErrorEnvelope"])}}}


def _get_post_response(get_schema: dict[str, Any], post_schema: dict[str, Any]) -> dict[str, Any]:
    return {
        "get": {"responses": {"200": _json_response(get_schema), "default": _json_response(API_SCHEMAS["ErrorEnvelope"])}},
        "post": {"responses": {"202": _json_response(post_schema), "default": _json_response(API_SCHEMAS["ErrorEnvelope"])}},
    }


def _json_response(schema: dict[str, Any]) -> dict[str, Any]:
    return {"description": "JSON response", "content": {"application/json": {"schema": schema}}}
