export const queryKeys = {
  summary: ['summary'] as const,
  eventDistribution: ['event-distribution'] as const,
  dailyEvents: ['daily-events'] as const,
  dailySales: ['daily-sales'] as const,
  topCategories: ['top-categories'] as const,
  topBrands: ['top-brands'] as const,
  dashboardSlice: (params: { event_type?: string; category_level1?: string; brand?: string }) =>
    ['dashboard-slice', params] as const,
  controlledQuery: ['controlled-query'] as const,
  conversionFunnel: ['conversion-funnel'] as const,
  conversionDaily: ['conversion-daily'] as const,
  productConversion: (limit: number) => ['product-conversion', limit] as const,
  journeySummary: ['journey-summary'] as const,
  journeyPaths: (limit: number) => ['journey-paths', limit] as const,
  journeyTransitions: (limit: number) => ['journey-transitions', limit] as const,
  journeyExitEvents: (limit: number) => ['journey-exit-events', limit] as const,
  journeyPurchasePaths: (limit: number) => ['journey-purchase-paths', limit] as const,
  optimizationSummary: ['optimization-summary'] as const,
  optimizationPlan: (limit: number) => ['optimization-plan', limit] as const,
  optimizationCandidates: (limit: number) => ['optimization-candidates', limit] as const,
  optimizationQuality: ['optimization-quality'] as const,
  recommendationSummary: ['recommendation-summary'] as const,
  recommendationItems: (limit: number) => ['recommendation-items', limit] as const,
  recommendationCandidates: (params: { source?: string; limit?: number }) => ['recommendation-candidates', params] as const,
  recommendationQuality: ['recommendation-quality'] as const,
  recommendationEvaluation: ['recommendation-evaluation'] as const,
  recommendationAlerts: ['recommendation-alerts'] as const,
  anomalySummary: ['anomaly-summary'] as const,
  anomalyAlerts: (limit: number) => ['anomaly-alerts', limit] as const,
  anomalyIncidents: (limit: number) => ['anomaly-incidents', limit] as const,
  anomalyRootCause: (params: { incident_id?: string }) => ['anomaly-root-cause', params] as const,
  anomalyEvaluation: ['anomaly-evaluation'] as const,
  anomalyTimeline: ['anomaly-timeline'] as const,
  anomalyRules: ['anomaly-rules'] as const,
  lifecycleSummary: ['lifecycle-summary'] as const,
  lifecycleSegments: ['lifecycle-segments'] as const,
  lifecycleRiskQueue: (limit: number) => ['lifecycle-risk-queue', limit] as const,
  lifecycleCategoryAffinity: (limit: number) => ['lifecycle-category-affinity', limit] as const,
  lifecycleRules: ['lifecycle-rules'] as const,
  experimentSummary: ['experiment-summary'] as const,
  experimentCatalog: ['experiment-catalog'] as const,
  experimentAssignments: (limit: number) => ['experiment-assignments', limit] as const,
  experimentSegments: ['experiment-segments'] as const,
  experimentGuardrails: ['experiment-guardrails'] as const,
  experimentResults: (params: { experiment_key?: string }) => ['experiment-results', params] as const,
  experimentUplift: (params: { experiment_key?: string }) => ['experiment-uplift', params] as const,
  featureMartSummary: ['feature-mart-summary'] as const,
  featureMartFreshness: ['feature-mart-freshness'] as const,
  featureMartQuality: ['feature-mart-quality'] as const,
  featureMartPartitions: ['feature-mart-partitions'] as const,
  featureMartFeatures: ['feature-mart-features'] as const,
  featureMartReadiness: ['feature-mart-readiness'] as const,
  featureMartProducts: (limit: number) => ['feature-mart-products', limit] as const,
  featureMartCategories: (limit: number) => ['feature-mart-categories', limit] as const,
  featureMartUsers: (limit: number) => ['feature-mart-users', limit] as const,
  forecastingSummary: ['forecasting-summary'] as const,
  forecastingSeries: (params: { scope?: string; entity?: string; metric?: string }) =>
    ['forecasting-series', params] as const,
  forecastingEntities: (limit: number) => ['forecasting-entities', limit] as const,
  forecastingBacktest: (params: { scope?: string; entity?: string }) => ['forecasting-backtest', params] as const,
  forecastingEvaluation: ['forecasting-evaluation'] as const,
  forecastingRisks: (params: { severity?: string; limit?: number }) => ['forecasting-risks', params] as const,
  forecastingQuality: ['forecasting-quality'] as const,
  affinitySummary: ['affinity-summary'] as const,
  affinityNodes: (params: { entity_type?: string; q?: string; limit?: number }) => ['affinity-nodes', params] as const,
  affinityEdges: (params: { entity_id?: string; relation_type?: string; limit?: number }) =>
    ['affinity-edges', params] as const,
  affinityCommunities: (limit: number) => ['affinity-communities', limit] as const,
  affinityOpportunities: (params: { type?: string; confidence?: number; limit?: number }) =>
    ['affinity-opportunities', params] as const,
  affinityCentrality: (params: { community_id?: string; limit?: number }) => ['affinity-centrality', params] as const,
  affinityQuality: ['affinity-quality'] as const,
  cohortSummary: ['cohort-summary'] as const,
  cohortRetention: (params: { cohort?: string; metric?: string }) => ['cohort-retention', params] as const,
  cohortValueCurves: (params: { cohort?: string }) => ['cohort-value-curves', params] as const,
  cohortRepurchaseIntervals: ['cohort-repurchase-intervals'] as const,
  cohortSegments: (params: { category?: string; limit?: number }) => ['cohort-segments', params] as const,
  cohortQuality: ['cohort-quality'] as const,
  portfolioSummary: ['portfolio-summary'] as const,
  portfolioCategories: (limit: number) => ['portfolio-categories', limit] as const,
  portfolioBrands: (params: { category?: string; limit?: number }) => ['portfolio-brands', params] as const,
  portfolioPriceBands: (params: { category?: string; price_band?: string }) =>
    ['portfolio-price-bands', params] as const,
  portfolioProducts: (params: { category?: string; brand?: string; limit?: number }) =>
    ['portfolio-products', params] as const,
  portfolioConcentration: ['portfolio-concentration'] as const,
  portfolioOpportunities: (params: { type?: string; confidence?: number; limit?: number }) =>
    ['portfolio-opportunities', params] as const,
  portfolioQuality: ['portfolio-quality'] as const,
  cartSummary: ['cart-summary'] as const,
  cartCategories: (limit: number) => ['cart-categories', limit] as const,
  cartProducts: (params: { category?: string; brand?: string; limit?: number }) => ['cart-products', params] as const,
  cartRecoveryQueue: (params: { action?: string; confidence?: number; limit?: number }) =>
    ['cart-recovery-queue', params] as const,
  cartQuality: ['cart-quality'] as const,
  attributionSummary: ['attribution-summary'] as const,
  attributionModels: (params: { entity_type?: string }) => ['attribution-models', params] as const,
  attributionEntities: (params: { entity_type?: string; model?: string; limit?: number }) =>
    ['attribution-entities', params] as const,
  attributionPaths: (limit: number) => ['attribution-paths', limit] as const,
  attributionAssists: (params: { entity_type?: string; limit?: number }) => ['attribution-assists', params] as const,
  attributionQuality: ['attribution-quality'] as const,
  job: ['job'] as const,
  jobs: (limit: number) => ['jobs', limit] as const,
  jobDetail: (jobId: string) => ['jobs', jobId] as const,
  jobLineage: (jobId: string) => ['jobs', jobId, 'lineage'] as const,
  jobQuality: (jobId: string) => ['jobs', jobId, 'quality'] as const,
  opsEvidence: ['ops-evidence'] as const,
  optimizationImpact: ['optimization-impact'] as const,
  liveWeatherCurrent: ['live-weather-current'] as const,
  liveWeatherForecast: ['live-weather-forecast'] as const,
  liveWeatherSummary: ['live-weather-summary'] as const,
  liveTrainingStatus: ['live-training-status'] as const,
  liveTrainingMetrics: ['live-training-metrics'] as const,
  liveTrainingImpact: ['live-training-impact'] as const,
  liveTrainingForecastImpact: ['live-training-forecast-impact'] as const,
  table: (params: { page: number; size: number; event_type?: string; category_level1?: string; brand?: string }) => ['table', params] as const,
};
