use std::collections::VecDeque;

use serde::Serialize;

#[derive(Debug, Default, Clone, Serialize)]
pub(crate) struct GatewayMetrics {
    pub(crate) market_events: u64,
    pub(crate) order_events: u64,
    pub(crate) market_redis_publish_failures: u64,
    pub(crate) market_stream_events: u64,
    pub(crate) market_stream_publish_failures: u64,
    pub(crate) last_market_stream_id: Option<String>,
    pub(crate) last_market_event_at: Option<u64>,
    pub(crate) last_order_event_at: Option<u64>,
    pub(crate) last_market_ingest_error: Option<String>,
    pub(crate) last_order_ingest_error: Option<String>,
    pub(crate) http_requests_total: u64,
    pub(crate) http_requests_4xx: u64,
    pub(crate) http_requests_5xx: u64,
    pub(crate) last_http_latency_ms: Option<u64>,
    pub(crate) http_latency_samples_ms: VecDeque<u64>,
    pub(crate) order_stream_events: u64,
    pub(crate) order_stream_ack_failures: u64,
    pub(crate) order_stream_read_failures: u64,
    pub(crate) order_stream_retry_attempts: u64,
    pub(crate) order_stream_fallbacks: u64,
    pub(crate) order_stream_consecutive_failures: u64,
    pub(crate) last_order_stream_retry_backoff_ms: Option<u64>,
    pub(crate) last_order_stream_id: Option<String>,
    pub(crate) order_stream_pending: u64,
    pub(crate) order_stream_lag: u64,
    pub(crate) order_stream_reclaim_attempts: u64,
    pub(crate) order_stream_reclaimed_events: u64,
    pub(crate) order_stream_reclaim_failures: u64,
    pub(crate) order_stream_poisoned_events: u64,
    pub(crate) last_order_stream_reclaim_at: Option<u64>,
    pub(crate) last_order_stream_poison_id: Option<String>,
    pub(crate) strategy_upstream_requests_total: u64,
    pub(crate) strategy_upstream_failures_total: u64,
    pub(crate) strategy_upstream_auth_failures_total: u64,
    pub(crate) strategy_upstream_circuit_rejections_total: u64,
    pub(crate) strategy_upstream_queue_rejections_total: u64,
    pub(crate) strategy_upstream_circuit_open: bool,
    pub(crate) strategy_upstream_circuit_opened_at: Option<u64>,
    pub(crate) strategy_upstream_last_error: Option<String>,
    pub(crate) strategy_summary_cache_hits: u64,
    pub(crate) strategy_summary_cache_misses: u64,
    pub(crate) strategy_summary_coalesced_waits: u64,
}
