from vertexai.generative_models import GenerativeModel, SafetySetting
import json
import logging
from app.core.config import settings

logger = logging.getLogger(__name__)

class AIJudge:
    """
    LLM-as-a-Judge Service (AI Governance)
    Uses a powerful model (Gemini 1.5 Pro) to audit content generated by other agents.
    """
    
    def __init__(self):
        # Use a more capable model for judging
        self.model_name = "gemini-1.5-pro-001" 
        try:
            self.model = GenerativeModel(self.model_name)
        except Exception as e:
            logger.warning(f"Failed to initialize Judge model {self.model_name}: {e}")
            self.model = None

    def evaluate_email_quality(self, email_content: str, user_risk_level: str) -> dict:
        """
        Evaluates the quality and compliance of a generated email.
        """
        if not self.model:
            return {"score": 0, "reason": "Judge Service Unavailable", "is_compliant": False}

        prompt = f"""
        你是一个严苛的 AI 合规审计员 (AI Judge)。
        请评估以下这封发给【{user_risk_level}风险】用户的挽留邮件。
        
        待审计邮件内容:
        ---
        {email_content}
        ---
        
        请检查以下合规性维度：
        1. 虚假承诺: 是否包含了不属于公司政策的虚假优惠？
        2. 语气恰当性: 语气是否过于激进、卑微或不专业？
        3. 方案具体性: 是否提供了具体的挽留方案而非空话？
        4. 信息安全: 是否泄露了不该泄露的内部数据？

        请严格打分 (0-100)，并给出简短的审计意见。
        
        Output JSON format ONLY:
        {{
            "score": <int>,
            "reason": "<string>",
            "is_compliant": <bool>
        }}
        """
        
        try:
            response = self.model.generate_content(
                prompt,
                generation_config={"response_mime_type": "application/json"}
            )
            
            result = json.loads(response.text)
            logger.info(f"AI Judge Evaluation: {result}")
            return result
            
        except Exception as e:
            logger.error(f"AI Judge evaluation failed: {e}")
            # Fallback for error cases
            return {
                "score": 50, 
                "reason": "Audit process failed due to technical error.", 
                "is_compliant": False
            }

    def evaluate_response(self, user_profile: dict, generated_email: str, applied_policies: list) -> dict:
        """
        Legacy wrapper for compatibility if needed, or extended logic.
        Currently redirects to evaluate_email_quality.
        """
        user_risk = "High" if user_profile.get("predicted_label") == 1 else "Low"
        return self.evaluate_email_quality(generated_email, user_risk)
