from __future__ import annotations

import sys
from pathlib import Path

# gRPC Python stubs generated by buf import from top-level `cerberus.*`.
# Ensure generated root is importable without relying on global PYTHONPATH.
GEN_ROOT = Path(__file__).resolve().parent / "gen"
if str(GEN_ROOT) not in sys.path:
    sys.path.insert(0, str(GEN_ROOT))

from cerberus.order.v1 import order_pb2, order_pb2_grpc  # noqa: E402

__all__ = ["order_pb2", "order_pb2_grpc"]
