#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${1:-$(gcloud config get-value project 2>/dev/null || true)}"
REGION="${2:-asia-east2}"
SERVICE_NAME="${SERVICE_NAME:-cerberus-strategy}"
SOURCE_DIR="${SOURCE_DIR:-$(cd "$(dirname "$0")/../services/strategy-py" && pwd)}"

if [[ -z "${PROJECT_ID}" ]]; then
  echo "PROJECT_ID is required (arg1 or active gcloud project)." >&2
  exit 1
fi

CORS_ALLOW_ORIGINS="${CORS_ALLOW_ORIGINS:-https://cerberus-9d94f.web.app,https://cerberus-9d94f.firebaseapp.com}"
MARKET_CHANNEL="${MARKET_CHANNEL:-md.orderbook.BTCUSDT}"
MARKET_CHANNELS="${MARKET_CHANNELS:-md.orderbook.BTCUSDT,md.orderbook.ETHUSDT}"
SIGNAL_CHANNEL="${SIGNAL_CHANNEL:-strategy.signals.default}"
FIREBASE_ENABLED="${FIREBASE_ENABLED:-true}"
FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID:-cerberus-9d94f}"
FIREBASE_SIGNAL_COLLECTION="${FIREBASE_SIGNAL_COLLECTION:-strategy_signals}"
SUPABASE_ENABLED="${SUPABASE_ENABLED:-true}"
SUPABASE_SIGNAL_TABLE="${SUPABASE_SIGNAL_TABLE:-strategy_signals}"
SUPABASE_TIMEOUT_SECONDS="${SUPABASE_TIMEOUT_SECONDS:-5}"
MATCHING_ENABLED="${MATCHING_ENABLED:-false}"
MATCHING_GRPC_TARGET="${MATCHING_GRPC_TARGET:-localhost:50051}"
STRATEGY_ACCOUNT_ID="${STRATEGY_ACCOUNT_ID:-default}"
STRATEGY_ORDER_QUANTITY="${STRATEGY_ORDER_QUANTITY:-0.001}"
TRADE_EXECUTION_CHANNEL_PREFIX="${TRADE_EXECUTION_CHANNEL_PREFIX:-trade.executions}"
EXECUTION_RELAY_INTERVAL_SECONDS="${EXECUTION_RELAY_INTERVAL_SECONDS:-1.0}"
EXECUTION_RELAY_BATCH_LIMIT="${EXECUTION_RELAY_BATCH_LIMIT:-100}"
INFERENCE_ENABLED="${INFERENCE_ENABLED:-false}"
INFERENCE_MODE="${INFERENCE_MODE:-disabled}"
INFERENCE_ENGINE_NAME="${INFERENCE_ENGINE_NAME:-moving_average_baseline}"
INFERENCE_MODEL_ID="${INFERENCE_MODEL_ID:-moving-average-baseline}"
INFERENCE_MODEL_VERSION="${INFERENCE_MODEL_VERSION:-v1}"
INFERENCE_MODEL_SOURCE="${INFERENCE_MODEL_SOURCE:-runtime}"
INFERENCE_MODEL_SYMBOLS="${INFERENCE_MODEL_SYMBOLS:-}"
INFERENCE_ARTIFACT_FOLDER_URL="${INFERENCE_ARTIFACT_FOLDER_URL:-}"
INFERENCE_ARTIFACT_GCS_URI="${INFERENCE_ARTIFACT_GCS_URI:-}"
INFERENCE_PRIMARY_MIN_MACRO_F1="${INFERENCE_PRIMARY_MIN_MACRO_F1:-0.58}"
INFERENCE_PRIMARY_MIN_OBSERVE_TICKS="${INFERENCE_PRIMARY_MIN_OBSERVE_TICKS:-500}"
INFERENCE_PRIMARY_MIN_AGREEMENT_RATIO="${INFERENCE_PRIMARY_MIN_AGREEMENT_RATIO:-0.55}"
INFERENCE_ROLLOUT_FORCE_PRIMARY="${INFERENCE_ROLLOUT_FORCE_PRIMARY:-false}"
INFERENCE_AUDIT_MAX_EVENTS="${INFERENCE_AUDIT_MAX_EVENTS:-50}"

REDIS_URL_SECRET="${REDIS_URL_SECRET:-cerberus-upstash-redis-url}"
UPSTASH_REDIS_REST_URL_SECRET="${UPSTASH_REDIS_REST_URL_SECRET:-cerberus-upstash-redis-rest-url}"
UPSTASH_REDIS_REST_TOKEN_SECRET="${UPSTASH_REDIS_REST_TOKEN_SECRET:-cerberus-upstash-redis-rest-token}"
SUPABASE_PROJECT_URL_SECRET="${SUPABASE_PROJECT_URL_SECRET:-cerberus-supabase-project-url}"
SUPABASE_ANON_KEY_SECRET="${SUPABASE_ANON_KEY_SECRET:-cerberus-supabase-anon-key}"
SUPABASE_SERVICE_ROLE_KEY_SECRET="${SUPABASE_SERVICE_ROLE_KEY_SECRET:-cerberus-supabase-service-role-key}"
SUPABASE_DB_URL_SECRET="${SUPABASE_DB_URL_SECRET:-cerberus-supabase-db-url}"
GRB_LICENSEID_SECRET="${GRB_LICENSEID_SECRET:-cerberus-grb-licenseid}"
GRB_WLSACCESSID_SECRET="${GRB_WLSACCESSID_SECRET:-cerberus-grb-wlsaccessid}"
GRB_WLSSECRET_SECRET="${GRB_WLSSECRET_SECRET:-cerberus-grb-wlssecret}"

create_temp_env_file() {
  local prefix="$1"
  local base
  base="$(mktemp "${TMPDIR:-/tmp}/${prefix}.XXXXXX")"
  mv "${base}" "${base}.yaml"
  printf '%s.yaml\n' "${base}"
}

env_file="$(create_temp_env_file cerberus-strategy-env)"
cat >"${env_file}" <<YAML
CORS_ALLOW_ORIGINS: "${CORS_ALLOW_ORIGINS}"
MARKET_CHANNEL: ${MARKET_CHANNEL}
MARKET_CHANNELS: "${MARKET_CHANNELS}"
SIGNAL_CHANNEL: ${SIGNAL_CHANNEL}
FIREBASE_ENABLED: "${FIREBASE_ENABLED}"
FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
FIREBASE_SIGNAL_COLLECTION: ${FIREBASE_SIGNAL_COLLECTION}
SUPABASE_ENABLED: "${SUPABASE_ENABLED}"
SUPABASE_SIGNAL_TABLE: ${SUPABASE_SIGNAL_TABLE}
SUPABASE_TIMEOUT_SECONDS: "${SUPABASE_TIMEOUT_SECONDS}"
MATCHING_ENABLED: "${MATCHING_ENABLED}"
MATCHING_GRPC_TARGET: ${MATCHING_GRPC_TARGET}
STRATEGY_ACCOUNT_ID: ${STRATEGY_ACCOUNT_ID}
STRATEGY_ORDER_QUANTITY: "${STRATEGY_ORDER_QUANTITY}"
TRADE_EXECUTION_CHANNEL_PREFIX: ${TRADE_EXECUTION_CHANNEL_PREFIX}
EXECUTION_RELAY_INTERVAL_SECONDS: "${EXECUTION_RELAY_INTERVAL_SECONDS}"
EXECUTION_RELAY_BATCH_LIMIT: "${EXECUTION_RELAY_BATCH_LIMIT}"
INFERENCE_ENABLED: "${INFERENCE_ENABLED}"
INFERENCE_MODE: "${INFERENCE_MODE}"
INFERENCE_ENGINE_NAME: ${INFERENCE_ENGINE_NAME}
INFERENCE_MODEL_ID: ${INFERENCE_MODEL_ID}
INFERENCE_MODEL_VERSION: ${INFERENCE_MODEL_VERSION}
INFERENCE_MODEL_SOURCE: ${INFERENCE_MODEL_SOURCE}
INFERENCE_MODEL_SYMBOLS: "${INFERENCE_MODEL_SYMBOLS}"
INFERENCE_ARTIFACT_FOLDER_URL: "${INFERENCE_ARTIFACT_FOLDER_URL}"
INFERENCE_ARTIFACT_GCS_URI: "${INFERENCE_ARTIFACT_GCS_URI}"
INFERENCE_PRIMARY_MIN_MACRO_F1: "${INFERENCE_PRIMARY_MIN_MACRO_F1}"
INFERENCE_PRIMARY_MIN_OBSERVE_TICKS: "${INFERENCE_PRIMARY_MIN_OBSERVE_TICKS}"
INFERENCE_PRIMARY_MIN_AGREEMENT_RATIO: "${INFERENCE_PRIMARY_MIN_AGREEMENT_RATIO}"
INFERENCE_ROLLOUT_FORCE_PRIMARY: "${INFERENCE_ROLLOUT_FORCE_PRIMARY}"
INFERENCE_AUDIT_MAX_EVENTS: "${INFERENCE_AUDIT_MAX_EVENTS}"
YAML

echo "deploying ${SERVICE_NAME} from source: ${SOURCE_DIR}"
gcloud run deploy "${SERVICE_NAME}" \
  --project="${PROJECT_ID}" \
  --region="${REGION}" \
  --platform=managed \
  --allow-unauthenticated \
  --source="${SOURCE_DIR}" \
  --env-vars-file="${env_file}" \
  --set-secrets="REDIS_URL=${REDIS_URL_SECRET}:latest,UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL_SECRET}:latest,UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN_SECRET}:latest,SUPABASE_PROJECT_URL=${SUPABASE_PROJECT_URL_SECRET}:latest,SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY_SECRET}:latest,SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY_SECRET}:latest,SUPABASE_DB_URL=${SUPABASE_DB_URL_SECRET}:latest,GRB_LICENSEID=${GRB_LICENSEID_SECRET}:latest,GRB_WLSACCESSID=${GRB_WLSACCESSID_SECRET}:latest,GRB_WLSSECRET=${GRB_WLSSECRET_SECRET}:latest"

rm -f "${env_file}"
echo "deploy completed: ${SERVICE_NAME} (${PROJECT_ID}/${REGION})"
