import { type MouseEvent, useEffect, useMemo, useState } from "react";

interface CalibrationPoint {
  pixel_x: number;
  pixel_y: number;
  world_x: number;
  world_y: number;
}

interface CalibrationEntry {
  notes: string;
  position_rmse_floor_m: number;
  calibration_scale_uncertainty_pct: number;
  points: CalibrationPoint[];
}

const defaultWorldPoints = [
  { world_x: 0, world_y: 0 },
  { world_x: 24, world_y: 0 },
  { world_x: 24, world_y: 65 },
  { world_x: 0, world_y: 65 }
];

export function CalibrationWorkbench() {
  const [imageUrl, setImageUrl] = useState("");
  const [imageObjectUrl, setImageObjectUrl] = useState<string | null>(null);
  const [imageLoadFailed, setImageLoadFailed] = useState(false);
  const [imageSize, setImageSize] = useState({ width: 1280, height: 720 });
  const [clipName, setClipName] = useState("028_red_light_static_0008s_30s.mp4");
  const [positionRmseFloorM, setPositionRmseFloorM] = useState(0.75);
  const [scaleUncertaintyPct, setScaleUncertaintyPct] = useState(4);
  const [activeIndex, setActiveIndex] = useState(0);
  const [points, setPoints] = useState<CalibrationPoint[]>(
    defaultWorldPoints.map((point) => ({
      pixel_x: 0,
      pixel_y: 0,
      ...point
    }))
  );

  useEffect(
    () => () => {
      if (imageObjectUrl) {
        URL.revokeObjectURL(imageObjectUrl);
      }
    },
    [imageObjectUrl]
  );

  const calibrationEntry: CalibrationEntry = useMemo(
    () => ({
      notes: "Manual calibration from frontend workbench.",
      position_rmse_floor_m: positionRmseFloorM,
      calibration_scale_uncertainty_pct: scaleUncertaintyPct,
      points
    }),
    [points, positionRmseFloorM, scaleUncertaintyPct]
  );

  const exportPayload = useMemo(
    () => ({
      [clipName]: calibrationEntry
    }),
    [calibrationEntry, clipName]
  );

  const fullPresetPayload = useMemo(
    () => ({
      schema_version: 1,
      notes: "Generated by TrafficPerceptionEngine calibration workbench.",
      video_calibrations: exportPayload
    }),
    [exportPayload]
  );
  const activeImageSrc = imageObjectUrl ?? imageUrl.trim();

  function handleImageClick(event: MouseEvent<HTMLImageElement>) {
    const rect = event.currentTarget.getBoundingClientRect();
    const scaleX = event.currentTarget.naturalWidth / rect.width;
    const scaleY = event.currentTarget.naturalHeight / rect.height;
    setImageSize({
      width: event.currentTarget.naturalWidth,
      height: event.currentTarget.naturalHeight
    });
    const pixelX = (event.clientX - rect.left) * scaleX;
    const pixelY = (event.clientY - rect.top) * scaleY;
    setPoints((current) =>
      current.map((point, index) =>
        index === activeIndex
          ? { ...point, pixel_x: Number(pixelX.toFixed(2)), pixel_y: Number(pixelY.toFixed(2)) }
          : point
      )
    );
    setActiveIndex((activeIndex + 1) % points.length);
  }

  function updateWorldPoint(index: number, key: "world_x" | "world_y", value: string) {
    const numeric = Number(value);
    setPoints((current) =>
      current.map((point, pointIndex) =>
        pointIndex === index && Number.isFinite(numeric) ? { ...point, [key]: numeric } : point
      )
    );
  }

  function handleImageFile(file: File | undefined) {
    if (!file) {
      return;
    }
    setImageLoadFailed(false);
    setImageObjectUrl(URL.createObjectURL(file));
    setImageUrl(file.name);
  }

  function downloadJson(filename: string, payload: object) {
    const blob = new Blob([JSON.stringify(payload, null, 2)], {
      type: "application/json"
    });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = filename;
    anchor.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="calibration-workbench">
      <section className="panel wide">
        <div className="panel-heading">
          <h2>人工标定工作台</h2>
        </div>
        <div className="calibration-controls">
          <label>
            <span>视频文件名</span>
            <input onChange={(event) => setClipName(event.target.value)} value={clipName} />
          </label>
          <label>
            <span>标定帧路径</span>
            <input
              onChange={(event) => {
                setImageObjectUrl(null);
                setImageLoadFailed(false);
                setImageUrl(event.target.value);
              }}
              placeholder="选择本地标定图，或粘贴可访问 URL"
              value={imageUrl}
            />
          </label>
          <label>
            <span>选择标定图</span>
            <input
              accept="image/jpeg,image/png"
              onChange={(event) => handleImageFile(event.target.files?.[0])}
              type="file"
            />
          </label>
          <label>
            <span>位置 RMSE floor/m</span>
            <input
              onChange={(event) => setPositionRmseFloorM(Number(event.target.value))}
              step="0.05"
              type="number"
              value={positionRmseFloorM}
            />
          </label>
          <label>
            <span>尺度不确定性/%</span>
            <input
              onChange={(event) => setScaleUncertaintyPct(Number(event.target.value))}
              step="0.5"
              type="number"
              value={scaleUncertaintyPct}
            />
          </label>
        </div>
      </section>

      <section className="panel calibration-image-panel">
        <div className="panel-heading">
          <h2>{`点击 P${activeIndex + 1}`}</h2>
        </div>
        <div className="calibration-image-wrap">
          {activeImageSrc && !imageLoadFailed ? (
            <img
              alt="calibration frame"
              onClick={handleImageClick}
              onError={() => setImageLoadFailed(true)}
              onLoad={(event) => {
                setImageLoadFailed(false);
                setImageSize({
                  width: event.currentTarget.naturalWidth,
                  height: event.currentTarget.naturalHeight
                });
              }}
              src={activeImageSrc}
            />
          ) : (
            <div className="calibration-empty-state">选择一张标定帧后开始采集 P1-P4 控制点</div>
          )}
          {points.map((point, index) =>
            point.pixel_x > 0 || point.pixel_y > 0 ? (
              <span
                className={index === activeIndex ? "calibration-marker active" : "calibration-marker"}
                key={`${point.pixel_x}-${point.pixel_y}-${index}`}
                style={{
                  left: `${(point.pixel_x / imageSize.width) * 100}%`,
                  top: `${(point.pixel_y / imageSize.height) * 100}%`
                }}
              >
                {`P${index + 1}`}
              </span>
            ) : null
          )}
        </div>
      </section>

      <section className="panel">
        <div className="panel-heading">
          <h2>控制点</h2>
        </div>
        <div className="point-editor-list">
          {points.map((point, index) => (
            <div className={index === activeIndex ? "point-editor active" : "point-editor"} key={index}>
              <strong>{`P${index + 1}`}</strong>
              <span>{`px (${point.pixel_x.toFixed(2)}, ${point.pixel_y.toFixed(2)})`}</span>
              <label>
                <span>X/m</span>
                <input
                  onChange={(event) => updateWorldPoint(index, "world_x", event.target.value)}
                  type="number"
                  value={point.world_x}
                />
              </label>
              <label>
                <span>Y/m</span>
                <input
                  onChange={(event) => updateWorldPoint(index, "world_y", event.target.value)}
                  type="number"
                  value={point.world_y}
                />
              </label>
              <button className="secondary-button" onClick={() => setActiveIndex(index)} type="button">
                选择
              </button>
            </div>
          ))}
        </div>
      </section>

      <section className="panel wide">
        <div className="panel-heading">
          <h2>导出 JSON</h2>
          <div className="button-row">
            <button
              className="secondary-button"
              onClick={() => downloadJson(`${clipName}.calibration-entry.json`, exportPayload)}
              type="button"
            >
              下载片段
            </button>
            <button
              className="primary-button"
              onClick={() => downloadJson("calibration_presets.generated.json", fullPresetPayload)}
              type="button"
            >
              下载完整 preset
            </button>
          </div>
        </div>
        <pre className="report-output">{JSON.stringify(fullPresetPayload, null, 2)}</pre>
      </section>
    </div>
  );
}
