import { type MouseEvent, useEffect, useMemo, useState } from "react";

import { getCalibrationPreset, saveCalibrationPreset } from "../api/calibration";
import { listVideoSamples } from "../api/video";
import type { CalibrationEntry, CalibrationPoint, CalibrationSaveResult } from "../types/calibration";
import type { VideoSample } from "../types/videoTask";

const defaultWorldPoints = [
  { world_x: 0, world_y: 0 },
  { world_x: 24, world_y: 0 },
  { world_x: 24, world_y: 65 },
  { world_x: 0, world_y: 65 }
];

export function CalibrationWorkbench() {
  const [imageUrl, setImageUrl] = useState("");
  const [imageObjectUrl, setImageObjectUrl] = useState<string | null>(null);
  const [imageLoadFailed, setImageLoadFailed] = useState(false);
  const [imageSize, setImageSize] = useState({ width: 1280, height: 720 });
  const [clipName, setClipName] = useState("028_red_light_static_0008s_30s.mp4");
  const [samples, setSamples] = useState<VideoSample[]>([]);
  const [positionRmseFloorM, setPositionRmseFloorM] = useState(0.75);
  const [scaleUncertaintyPct, setScaleUncertaintyPct] = useState(4);
  const [activeIndex, setActiveIndex] = useState(0);
  const [saveResult, setSaveResult] = useState<CalibrationSaveResult | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [points, setPoints] = useState<CalibrationPoint[]>(
    defaultWorldPoints.map((point) => ({
      pixel_x: 0,
      pixel_y: 0,
      ...point
    }))
  );

  useEffect(
    () => () => {
      if (imageObjectUrl) {
        URL.revokeObjectURL(imageObjectUrl);
      }
    },
    [imageObjectUrl]
  );

  useEffect(() => {
    let isMounted = true;
    listVideoSamples()
      .then((nextSamples) => {
        if (!isMounted) {
          return;
        }
        setSamples(nextSamples);
        if (nextSamples.length > 0) {
          setClipName(nextSamples[0].name);
        }
      })
      .catch(() => {
        if (isMounted) {
          setSamples([]);
        }
      });
    return () => {
      isMounted = false;
    };
  }, []);

  useEffect(() => {
    let isMounted = true;
    if (!clipName) {
      return undefined;
    }
    getCalibrationPreset(clipName)
      .then((entry) => {
        if (!isMounted || !entry) {
          return;
        }
        setPositionRmseFloorM(entry.position_rmse_floor_m);
        setScaleUncertaintyPct(entry.calibration_scale_uncertainty_pct);
        setPoints(entry.points);
      })
      .catch(() => undefined);
    return () => {
      isMounted = false;
    };
  }, [clipName]);

  const calibrationEntry: CalibrationEntry = useMemo(
    () => ({
      notes: "Manual calibration from frontend workbench.",
      position_rmse_floor_m: positionRmseFloorM,
      calibration_scale_uncertainty_pct: scaleUncertaintyPct,
      points
    }),
    [points, positionRmseFloorM, scaleUncertaintyPct]
  );

  const exportPayload = useMemo(
    () => ({
      [clipName]: calibrationEntry
    }),
    [calibrationEntry, clipName]
  );

  const fullPresetPayload = useMemo(
    () => ({
      schema_version: 1,
      notes: "Generated by TrafficPerceptionEngine calibration workbench.",
      video_calibrations: exportPayload
    }),
    [exportPayload]
  );
  const activeImageSrc = imageObjectUrl ?? imageUrl.trim();

  function handleImageClick(event: MouseEvent<HTMLImageElement>) {
    const rect = event.currentTarget.getBoundingClientRect();
    const scaleX = event.currentTarget.naturalWidth / rect.width;
    const scaleY = event.currentTarget.naturalHeight / rect.height;
    setImageSize({
      width: event.currentTarget.naturalWidth,
      height: event.currentTarget.naturalHeight
    });
    const pixelX = (event.clientX - rect.left) * scaleX;
    const pixelY = (event.clientY - rect.top) * scaleY;
    setPoints((current) =>
      current.map((point, index) =>
        index === activeIndex
          ? { ...point, pixel_x: Number(pixelX.toFixed(2)), pixel_y: Number(pixelY.toFixed(2)) }
          : point
      )
    );
    setActiveIndex((activeIndex + 1) % points.length);
  }

  function updateWorldPoint(index: number, key: "world_x" | "world_y", value: string) {
    const numeric = Number(value);
    setPoints((current) =>
      current.map((point, pointIndex) =>
        pointIndex === index && Number.isFinite(numeric) ? { ...point, [key]: numeric } : point
      )
    );
  }

  function handleImageFile(file: File | undefined) {
    if (!file) {
      return;
    }
    setImageLoadFailed(false);
    setImageObjectUrl(URL.createObjectURL(file));
    setImageUrl(file.name);
  }

  async function saveToYaml() {
    setIsSaving(true);
    setSaveError(null);
    setSaveResult(null);
    try {
      const result = await saveCalibrationPreset({
        clip_name: clipName,
        ...calibrationEntry,
        frame_width: imageSize.width,
        frame_height: imageSize.height,
        grid_spacing_m: 5.0
      });
      setSaveResult(result);
    } catch (error) {
      setSaveError(error instanceof Error ? error.message : "保存标定失败");
    } finally {
      setIsSaving(false);
    }
  }

  function downloadJson(filename: string, payload: object) {
    const blob = new Blob([JSON.stringify(payload, null, 2)], {
      type: "application/json"
    });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = filename;
    anchor.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="calibration-workbench">
      <section className="panel wide">
        <div className="panel-heading">
          <h2>人工标定工作台</h2>
        </div>
        <div className="calibration-controls">
          <label>
            <span>真实样片</span>
            <select
              disabled={samples.length === 0}
              onChange={(event) => setClipName(event.target.value)}
              value={clipName}
            >
              {samples.map((sample) => (
                <option key={sample.name} value={sample.name}>
                  {sample.name}
                </option>
              ))}
            </select>
          </label>
          <label>
            <span>视频文件名</span>
            <input onChange={(event) => setClipName(event.target.value)} value={clipName} />
          </label>
          <label>
            <span>标定帧路径</span>
            <input
              onChange={(event) => {
                setImageObjectUrl(null);
                setImageLoadFailed(false);
                setImageUrl(event.target.value);
              }}
              placeholder="选择本地标定图，或粘贴可访问 URL"
              value={imageUrl}
            />
          </label>
          <label>
            <span>选择标定图</span>
            <input
              accept="image/jpeg,image/png"
              onChange={(event) => handleImageFile(event.target.files?.[0])}
              type="file"
            />
          </label>
          <label>
            <span>位置 RMSE floor/m</span>
            <input
              onChange={(event) => setPositionRmseFloorM(Number(event.target.value))}
              step="0.05"
              type="number"
              value={positionRmseFloorM}
            />
          </label>
          <label>
            <span>尺度不确定性/%</span>
            <input
              onChange={(event) => setScaleUncertaintyPct(Number(event.target.value))}
              step="0.5"
              type="number"
              value={scaleUncertaintyPct}
            />
          </label>
        </div>
      </section>

      <section className="panel calibration-image-panel">
        <div className="panel-heading">
          <h2>{`点击 P${activeIndex + 1}`}</h2>
        </div>
        <div className="calibration-image-wrap">
          {activeImageSrc && !imageLoadFailed ? (
            <img
              alt="calibration frame"
              onClick={handleImageClick}
              onError={() => setImageLoadFailed(true)}
              onLoad={(event) => {
                setImageLoadFailed(false);
                setImageSize({
                  width: event.currentTarget.naturalWidth,
                  height: event.currentTarget.naturalHeight
                });
              }}
              src={activeImageSrc}
            />
          ) : (
            <div className="calibration-empty-state">选择一张标定帧后开始采集 P1-P4 控制点</div>
          )}
          {points.map((point, index) =>
            point.pixel_x > 0 || point.pixel_y > 0 ? (
              <span
                className={index === activeIndex ? "calibration-marker active" : "calibration-marker"}
                key={`${point.pixel_x}-${point.pixel_y}-${index}`}
                style={{
                  left: `${(point.pixel_x / imageSize.width) * 100}%`,
                  top: `${(point.pixel_y / imageSize.height) * 100}%`
                }}
              >
                {`P${index + 1}`}
              </span>
            ) : null
          )}
        </div>
      </section>

      <section className="panel">
        <div className="panel-heading">
          <h2>控制点</h2>
        </div>
        <div className="point-editor-list">
          {points.map((point, index) => (
            <div className={index === activeIndex ? "point-editor active" : "point-editor"} key={index}>
              <strong>{`P${index + 1}`}</strong>
              <span>{`px (${point.pixel_x.toFixed(2)}, ${point.pixel_y.toFixed(2)})`}</span>
              <label>
                <span>X/m</span>
                <input
                  onChange={(event) => updateWorldPoint(index, "world_x", event.target.value)}
                  type="number"
                  value={point.world_x}
                />
              </label>
              <label>
                <span>Y/m</span>
                <input
                  onChange={(event) => updateWorldPoint(index, "world_y", event.target.value)}
                  type="number"
                  value={point.world_y}
                />
              </label>
              <button className="secondary-button" onClick={() => setActiveIndex(index)} type="button">
                选择
              </button>
            </div>
          ))}
        </div>
      </section>

      <section className="panel wide">
        <div className="panel-heading">
          <h2>保存标定</h2>
          <div className="button-row">
            <button
              className="primary-button"
              disabled={isSaving}
              onClick={() => void saveToYaml()}
              type="button"
            >
              {isSaving ? "保存中" : "保存到 YAML"}
            </button>
            <button
              className="secondary-button"
              onClick={() => downloadJson(`${clipName}.calibration-entry.json`, exportPayload)}
              type="button"
            >
              下载片段
            </button>
            <button
              className="primary-button"
              onClick={() => downloadJson("calibration_presets.generated.json", fullPresetPayload)}
              type="button"
            >
              下载完整 preset
            </button>
          </div>
        </div>
        {saveError && <p className="task-error">保存失败：{saveError}</p>}
        {saveResult && (
          <div className="calibration-diagnostics">
            <div>
              <span>标定来源</span>
              <strong>{saveResult.source}</strong>
            </div>
            <div>
              <span>质量分级</span>
              <strong>{saveResult.diagnostics.calibration_quality}</strong>
            </div>
            <div>
              <span>重投影 RMSE</span>
              <strong>{`${saveResult.diagnostics.reprojection_rmse_px.toFixed(3)} px`}</strong>
            </div>
            <div>
              <span>RANSAC 内点</span>
              <strong>{saveResult.diagnostics.inlier_count}</strong>
            </div>
            <div>
              <span>条件数</span>
              <strong>{saveResult.diagnostics.condition_number.toExponential(2)}</strong>
            </div>
            <div>
              <span>YAML 路径</span>
              <strong>{saveResult.preset_path}</strong>
            </div>
          </div>
        )}
        <pre className="report-output">{JSON.stringify(fullPresetPayload, null, 2)}</pre>
      </section>
    </div>
  );
}
