steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sentinel-serve:latest'
      - '-f'
      - 'ml_engine/Dockerfile.serve'
      - '.'
    timeout: 1200s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sentinel-serve:latest']
images:
  - 'gcr.io/$PROJECT_ID/sentinel-serve:latest'
