DEFAULT_FRAME_BUFFER_SIZE = 120
DEFAULT_CONFIDENCE_THRESHOLD = 0.25
DEFAULT_IOU_THRESHOLD = 0.45
DEFAULT_MAX_SPEED_KMH = 200.0
DEFAULT_MIN_DISPLACEMENT_M = 0.1
DEFAULT_REPORT_INTERVAL = 1
DEFAULT_PAGE_SIZE = 100
MAX_UPLOAD_SIZE_MB = 512
