from __future__ import annotations

from copy import deepcopy
from pathlib import Path
from typing import Any

import yaml
from domain.calibration.models import CalibrationPoint
from domain.calibration.service import CalibrationService

PROJECT_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CALIBRATION_PRESET_PATH = PROJECT_ROOT / "data/tests/calibration_presets.yaml"


class CalibrationPresetStore:
    def __init__(self, path: Path = DEFAULT_CALIBRATION_PRESET_PATH) -> None:
        self.path = path
        self._service = CalibrationService()

    def list_entries(self) -> dict[str, Any]:
        payload = self._load_payload()
        return {
            "preset_path": str(self.path),
            "scene_profiles": payload.get("scene_profiles", {}),
            "video_calibrations": payload.get("video_calibrations", {}),
        }

    def get_entry(self, clip_name: str) -> dict[str, Any] | None:
        calibrations = self._load_payload().get("video_calibrations", {})
        entry = calibrations.get(self._safe_clip_name(clip_name))
        return deepcopy(entry) if isinstance(entry, dict) else None

    def upsert_entry(
        self,
        clip_name: str,
        entry: dict[str, Any],
        *,
        frame_width: int | None = None,
        frame_height: int | None = None,
        grid_spacing_m: float = 5.0,
    ) -> dict[str, Any]:
        safe_clip_name = self._safe_clip_name(clip_name)
        normalized_entry = self._normalize_entry(entry)
        diagnostics = self.validate_entry(
            normalized_entry,
            frame_width=frame_width,
            frame_height=frame_height,
            grid_spacing_m=grid_spacing_m,
        )
        payload = self._load_payload()
        calibrations = payload.setdefault("video_calibrations", {})
        calibrations[safe_clip_name] = normalized_entry
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(
            yaml.safe_dump(payload, allow_unicode=True, sort_keys=False),
            encoding="utf-8",
        )
        return {
            "clip_name": safe_clip_name,
            "source": "video_manual_preset",
            "entry": normalized_entry,
            "diagnostics": diagnostics,
            "preset_path": str(self.path),
        }

    def validate_entry(
        self,
        entry: dict[str, Any],
        *,
        frame_width: int | None = None,
        frame_height: int | None = None,
        grid_spacing_m: float = 5.0,
    ) -> dict[str, Any]:
        normalized_entry = self._normalize_entry(entry)
        points = [
            CalibrationPoint(
                pixel_x=point["pixel_x"],
                pixel_y=point["pixel_y"],
                world_x=point["world_x"],
                world_y=point["world_y"],
            )
            for point in normalized_entry["points"]
        ]
        homography = self._service.compute_homography_ransac(points, random_seed=11)
        world_xs = [point.world_x for point in points]
        world_ys = [point.world_y for point in points]
        world_width_m = max(world_xs) - min(world_xs)
        world_length_m = max(world_ys) - min(world_ys)
        diagnostics: dict[str, Any] = {
            "homography_model": "RANSAC planar homography, pixel(u,v) -> ground(X,Y)",
            "calibration_source": "video_manual_preset",
            "calibration_quality": homography.calibration_quality,
            "reprojection_rmse_px": homography.reprojection_rmse,
            "inlier_count": homography.inlier_count,
            "condition_number": homography.condition_number,
            "inlier_mask": homography.inlier_mask,
            "position_rmse_m": normalized_entry["position_rmse_floor_m"],
            "scale_uncertainty_pct": normalized_entry["calibration_scale_uncertainty_pct"],
            "world_width_m": world_width_m,
            "world_length_m": world_length_m,
            "model_reference": "Model 1 + Model 6",
        }
        if frame_width and frame_height and world_width_m > 0 and world_length_m > 0:
            grid = self._service.build_homography_grid(
                homography,
                frame_width=frame_width,
                frame_height=frame_height,
                world_width_m=world_width_m,
                world_length_m=world_length_m,
                spacing_m=grid_spacing_m,
            )
            diagnostics["homography_grid"] = grid.to_dict()
        return diagnostics

    def _load_payload(self) -> dict[str, Any]:
        if not self.path.exists():
            return {
                "schema_version": 1,
                "notes": "Generated by TrafficPerceptionEngine calibration workbench.",
                "scene_profiles": {},
                "video_calibrations": {},
            }
        payload = yaml.safe_load(self.path.read_text(encoding="utf-8"))
        return payload if isinstance(payload, dict) else {}

    @staticmethod
    def _normalize_entry(entry: dict[str, Any]) -> dict[str, Any]:
        points = entry.get("points")
        if not isinstance(points, list):
            raise ValueError("points must be a list")
        normalized_points: list[dict[str, float]] = []
        for point in points:
            if not isinstance(point, dict):
                raise ValueError("each calibration point must be an object")
            normalized_points.append(
                {
                    "pixel_x": float(point["pixel_x"]),
                    "pixel_y": float(point["pixel_y"]),
                    "world_x": float(point["world_x"]),
                    "world_y": float(point["world_y"]),
                },
            )
        return {
            "notes": str(entry.get("notes", "Manual calibration from frontend workbench.")),
            "position_rmse_floor_m": float(entry.get("position_rmse_floor_m", 1.0)),
            "calibration_scale_uncertainty_pct": float(
                entry.get("calibration_scale_uncertainty_pct", 5.0),
            ),
            "points": normalized_points,
        }

    @staticmethod
    def _safe_clip_name(clip_name: str) -> str:
        safe_name = Path(clip_name).name
        if not safe_name.endswith(".mp4"):
            raise ValueError("clip_name must be an MP4 filename")
        return safe_name
